### ISSUE TITLE
Missing data

### ISSUE THREAD

**Issue by superblyb** [softsyst/qirx_issues#100]
Auf 9C zeigt "9C" in den Niederlanden die korrekten TII-Daten, aber keine Entfernungen, und auf der Karte fehlen alle Daten. Ich habe noch nicht überprüft, ob dies dauerhaft der Fall ist.
Das Ensemble kommt sehr stark durch. Dies ist auch der Fall für 7C Brab / Limb.

On 9C, "9C" in the Netherlands shows the correct TII data, but no distances, and the map is missing all data. I have not yet verified whether this is persistently the case.
The ensemble comes through very strongly. This is also the case on 7C Brab / Limb.

https://goopics.net/i/s09oqh

**Comment by WIHDIA** [comment]
Hi superblyb

Odd as it's showing the data on 9C and 7C  here in central BEL.
QIRX version 4.0.9?

https://i.goopics.net/s9gj3d.jpg

https://i.goopics.net/w7gt8r.jpg

73 

Herman
[My logblog](https://wijnants.info/fmdx/)
Belgium editor [fmlist.org](https://www.fmlist.org/)

**Comment by andimik** [comment]
9C seems to use two TII main codes: 19xx and 29xx.

![_20230704_101801](https://github.com/softsyst/qirx_issues/assets/24510556/f925bf49-f05e-4969-b77d-bbe1a33cb22d)

**Comment by superblyb** [comment]
@Herman yes, newest version.

**Comment by superblyb** [comment]
7C is different:
https://goopics.net/i/2yk4ac

**Comment by WIHDIA** [comment]
7C shows locations on the map.
https://i.goopics.net/3ye7je.jpg
Did you update the DB?

73

Herman
[My logblog](https://wijnants.info/fmdx/)
Belgium editor [fmlist.org](https://www.fmlist.org/)

**Comment by superblyb** [comment]
Good thinking Herman, it seems there lies the problem in my case. I'm getting an error message there:

https://goopics.net/i/emd3sp

So I'm going to see to this now (trying to fix my database). I updated the database sevral times lately, and maybe something went wrong.

**Comment by andimik** [comment]
@superblyb

You can attach pictures in github.com

No need for an external provider.

**Comment by superblyb** [comment]
My problem is solved. Qirx could not find the database. I restarted my computer, downloaded the initial database again with qirx and updated it.  Everything is now working perfectly again.
I have no idea how my problem occurred. As far as I am concerned, this issue can be closed. Thank you both for your help.

**Comment by superblyb** [comment]
![7cnew](https://github.com/softsyst/qirx_issues/assets/129985820/f609d334-a9d9-4774-b9f8-0a288ee2dce1)
