### ISSUE TITLE
qirx 

### ISSUE THREAD

**Issue by JeffKitching** [softsyst/qirx_issues#101]
I'm using QIRX when out and about and I like to make a  .raw file of a mux when out on location. I find it frustrating when QIRX refuses to display the mux info under the tab. I have no problem with National/Local mux's in the UK. but the new SSDAB mux's refuse to load and I was wondering if its a problem with the Mux, thanks, Jeff Kitching

![356194020_10230571660744615_8724004060770164092_n](https://github.com/softsyst/qirx_issues/assets/139956613/1d3503ae-7154-47fd-afcc-50635bd781c5)

**Comment by softsyst** [comment]
A right mouse click offers the "Refresh" menu. Please see #69 and the discussion there. It's been the same issue.
