### ISSUE TITLE
Sorting

### ISSUE THREAD

**Issue by WIHDIA** [softsyst/qirx_issues#102]
Hi Clem,

I don't know if this has been mentioned before, but could the scan sorting be a bit more logical, not starting with 10A but 5A? 

After 3 hours of scanning two fake muxes were detected, but of course not entered in the log file. I know this has been mentioned before and as I said before, it's not easy to catch this in a  raw recording. Apart from this QIRX 4.0.9+ RTL-SDR is a great combo.

![afbeelding](https://github.com/softsyst/qirx_issues/assets/53539654/8ff8c1e6-9bff-4e6b-a896-47c67e082e5f)

73
Kind regards

Herman Wijnants

[My logblog](https://www.wijnants.info/fmdx/)
Belgium editor [fmlist.org](https://www.fmlist.org/)

**Comment by softsyst** [comment]
Hi Herman,

The good news: Sorting is already possible by clicking on the column's header (although it displays no "Sorting" triangle). 
The bad news: The "Block" column sorting is probably not what you want, as it is sorted by character, not by hex number what is necessary.

I'll consider it for the next version, should not be a big deal. Thanks for the input.

73,
Clem

**Comment by andimik** [comment]
Channel numbers are not Hex

**Comment by softsyst** [comment]
> Channel numbers are not Hex

Right, but to satisfy Herman's request, they should be sorted as if they were. IMO, the sorting should be the same as in the Block selector combo box.
The 'N' channels like 10N are not expected to show up in any scan.
The "correct" way could be to first transform the block number to a frequency, and then sort according to the frequency. In this way the 'N' channels also would show up on their correct positions.

**Comment by softsyst** [comment]
Should work in 4.1.1

**Comment by softsyst** [comment]
Herman, is it ok for you?

**Comment by softsyst** [comment]
No more comments. Closed.
