### ISSUE TITLE
Adding the short-label

### ISSUE THREAD

**Issue by Drehrumbum** [softsyst/qirx_issues#106]
Hi Clem!

Can you add the SHORTLABEL after the service-name, please? This would be really nice.

![6C_LE](https://github.com/softsyst/qirx_issues/assets/86889245/089582b1-0448-4f30-95f3-97fb0eb5d730)

**Comment by softsyst** [comment]
Heiko,

Great suggestion. I had a quick look, and it seems to be a lot of fun. 
I (perhaps you too) still know the times where variables in SW programs were restricted to 8 characters. 
As this training from the old times faded away, I am still struggling:

- Radio Da    ( Children's program, Radio Dada?)
- ARA BY       ( Arab, or Bavarian parrot?)
- BRSchlgr    ( A boring one from Bavaria)
- SSL             ( For us nerds, Secure Socket Layer)
- Verkehr      ( After midnight)

Clem

PS "Otto" might help: "I am hungry" : "Ich bin Ungar".....

**Comment by Drehrumbum** [comment]
PS: Clem, please do not strip out "spaces" (or other ASCII-stuff) in front of the "short-label". I wanna see who plays with such stuff. THX.

**Comment by softsyst** [comment]
See the discussion in #117. Closing this one.
