### ISSUE TITLE
New feature request - FF the raw-file

### ISSUE THREAD

**Issue by KoeKone** [softsyst/qirx_issues#107]
This is not a normal use... Meteor Scatter DX:ing using QIRX  (see https://youtu.be/9kiJsLIAzWY )

..but since I'm recording long files, hoping those meteor scatters to be caught (the only last for a few seconds). When recording, I am away/sleeping and I do not have any clue, if or when those short signal bursts would appear in the raw-file. It would be very useful to be able to FF the file.

By FF the raw file, I mean fast forwarding of the file, for example 8x playback etc, to quickly browse it and see if something would appear in the waterfall. The return to a normal 1x speed playback trying to lock into a signal, if a brief burst was found.

Best regards,

holmch/KoeKone

**Comment by softsyst** [comment]
First of all, congrats to your great success with the Perseid Meteor Scatter!
Although not being "normal use", it seems to be a good feature for your use-case. I can't give a realization date, but I'll consider it for one of the next versions.

Thanks for the input!
Clem

**Comment by Drehrumbum** [comment]
Very cool, well done!

@KoeKone: Just take a short look...   
https://www.rundfunkforum.de/viewtopic.php?f=11&t=61825
Can you edit out the short meteor events seen in your YT video from the IQ-recordings? Let's say 30 secs - the event in the middle? I would like to look at the recordings.

**Comment by softsyst** [comment]
Please check it in 4.1.1

**Comment by softsyst** [comment]
No new entry. I close this.
