### ISSUE TITLE
New feature request - DVB-T/T2 interface

### ISSUE THREAD

**Issue by KoeKone** [softsyst/qirx_issues#108]
As a DX'er, just a wild idea, 

It would be amazing to have an DVB-T/T2 interface with same kind of detailed interface and info than the DAB+.
This would only work with a SDR-receiver with bandwidth of 8 MHz or more, of course, but it woulb be a very desired feature for many DXers I know. 

Some related to subject DVB-T DX:ing here 
https://youtu.be/yRbCAdvE7Xc

Best regards, 
holmch/KoeKone from Finland

**Comment by softsyst** [comment]
Although this would be a highly attractive feature, I'll most probably not consider it for realization, for the time being. It certainly would block for some time other developments, as it would be a - more or less - completely new development.
Anyway, thanks for the input!

Clem

**Comment by andimik** [comment]
@KoeKone 

For DVB-T and DVB-T2 there is plenty software for hardware solutions, under Linux, Windows, Mac and even Android.

For example VLC Player, DVB Viewer, Transedit, etc. 

I don't see a reason why you want to do that in software.
