### ISSUE TITLE
New feature request - Analog tv interface with PAL/SECAM colour demulation

### ISSUE THREAD

**Issue by KoeKone** [softsyst/qirx_issues#109]
As a DX'er, just another wild idea, 

It would be amazing to have an analogue tv interface like the one in **PAL/Secam Plugin in the AirSpy SDR Sharp** or the stand alone Windows program **TV Sharp**

This would only work with a SDR-receiver with bandwidth of 8 MHz or more, of course, but it would be very desired feature for many DXers I know. Especially if PAL/SECAM colour demodulating could be implemented.

Some related to subject analoque DX:ing here:

https://youtu.be/ru5GgR7VSBk
https://youtu.be/dWCqfDIdrAg
https://youtu.be/TQbrBgq10lU
https://youtu.be/cNQGysGI3MM

As you can see, analoque tv is still alive and kicking!

Best regards, 
holmch/KoeKone from Finland

**Comment by softsyst** [comment]
This will certainly not be investigated, as it would be very hard to get test signals for a development. Otherwise, see #108.

Clem
