### ISSUE TITLE
Waterfall Time Code showing current time while playing a recorded raw file (DAB)

### ISSUE THREAD

**Issue by KoeKone** [softsyst/qirx_issues#110]
Related to the new feature request - FF the raw-file #107 ; 
While playing a recorded raw-file and selecting Waterfall Time Code, to see the timestamps within that recording, the time codes however show the current time, not the file recording time. It would be useful to see the timestamps of the actual recording time.

**Comment by Drehrumbum** [comment]
Hi folks!
There is one more point regarding the waterfall display during playback of previously recorded IQ files: It would be nice if the waterfall display also stopped when you paused the playback.

**Comment by softsyst** [comment]
Heiko,

Although your remark is of course valid, please in the future do not mix different issues in the same thread. Now, for your observation I opened a new one.

Clem

**Comment by softsyst** [comment]
Both should be fixed in 4.1.1

**Comment by softsyst** [comment]
Could someone check please!

**Comment by softsyst** [comment]
No more comments. Closed.
