### ISSUE TITLE
Losing own position (location coordinates) after playing a recorded raw-file

### ISSUE THREAD

**Issue by KoeKone** [softsyst/qirx_issues#111]
Hello, 
I have a fixed listening location and I do NOT have a GNSS sensor, hence I have manually inserted my own location into the configuration file. 
<OwnPosition Latitude="60.451759" Longitude="22.276927" />

It works and on the map I can then see my own location as an orange dot. When starting to receive TII data, also the received station shows up. A very nice feature!

However, if I play an recorded raw-file, I will Immediately loose my own fixed position during the playback from the configuration file. When returning to live listening mode, the location is also lost. 
<OwnPosition Latitude="0.000000" Longitude="0.000000" />

This is quite annoying and I hope it could be fixed.

Kind regards, 
holmch/Koekone

**Comment by softsyst** [comment]
No need to manually tinkering with the config file. Why just not drag'n drop the red dot with the mouse, directly on the map??

**Comment by KoeKone** [comment]
Yes, but the position is still lost every time i play a recorded file. Could this be fixed?

**Comment by softsyst** [comment]
Nothing to fix here.
If you do not use a GNSS sensor (as you write), you should not use the GNSS file together with the raw file. If you omit it (as it has no use), the own location should stay in place.
If this is not your scenario, please elaborate in a little more detail.

**Comment by KoeKone** [comment]
Ok, it works when selecting only the raw file. I was somehow under the impression from an experiment with an earlier version, that both files are needed for playback, otherwise I experienced a program crash. But after installing the latest 4.09 it plays fine with only the raw-file. And now it does not lose the position. SOLVED, thank you :-)

**Comment by KoeKone** [comment]
SOLVED, thank you :-)
