### ISSUE TITLE
Audio-spectrum: Impossible peak levels

### ISSUE THREAD

**Issue by Drehrumbum** [softsyst/qirx_issues#115]
Hi Clem,

in the audio-spectrum, the peak-line sometimes indicates impossible levels. You only have to wait for a little while. See below. Not so important, but good to know, if one will take a picture: Resizing the spectrum-window will erase the previous peak-lines, as if you had pressed "Clear".

Greetings Heiko

![audio-spec1](https://github.com/softsyst/qirx_issues/assets/86889245/cf2c7fb7-3a93-4559-afa1-1259c2130418)
![audio-spec2](https://github.com/softsyst/qirx_issues/assets/86889245/6a3cd24a-e95b-4c0f-968a-1bd7a67c9f96)

**Comment by softsyst** [comment]
Hi Heiko,

I know the case with the faulty values. Unfortunately not easy to find.
Resizing works here without problem. No erasure of the max values.

Clem

**Comment by softsyst** [comment]
Should be fixed in 4.1.3. I close it.

**Comment by Drehrumbum** [comment]
Hi Clem!

Mmm. The scaling of the Y-axis can't be right.

Greetings Heiko

![audio-spec](https://github.com/softsyst/qirx_issues/assets/86889245/f705777f-86b4-4f26-a40c-6ee70b1aef0c)

**Comment by softsyst** [comment]
Hi Heiko,
please open a new issue for this, as I hope the max issue to be fixed. The scaling is wrong since the introduction of the Time Domain possibility in the audio spectrum. Thanks for remarking! 

Greetz
Clem

**Comment by softsyst** [comment]
Fixed in 4.2.1
