### ISSUE TITLE
Service Tab shows previous selected service

### ISSUE THREAD

**Issue by andimik** [softsyst/qirx_issues#116]
When I change a frequency nearly everything is cleared, but no so the tab "Service".

It will show the previous heard service. In the screenshots, you will see ARS from Slovenia and Radio Austria from Austria.

![Screenshot (415)](https://github.com/softsyst/qirx_issues/assets/24510556/69d32d97-da31-459f-aeeb-f90f80a1aaf4)
![Screenshot (416)](https://github.com/softsyst/qirx_issues/assets/24510556/6a1c51bf-5acf-4873-a9a4-3953ff5a2f5b)

**Comment by softsyst** [comment]
I can confirm that the old logo sometimes is not cleared. The other items of the Service tab are cleared. The easiest way to clear the old logo is to select a service. I will consider this (at a low priority) for the next release.

**Comment by softsyst** [comment]
Fixed in 4.1.3. I close it.
