### ISSUE TITLE
Changed SPI-Thumbnail will not be updated

### ISSUE THREAD

**Issue by andimik** [softsyst/qirx_issues#119]
When a service got a new logo in SPI (in my case nationwide Technikum ONE got Radio ONE), this will not be updated in Qirx. The reason is that both logos are kept in the folder.

![grafik](https://github.com/softsyst/qirx_issues/assets/24510556/d4525dcc-6e6d-4224-b437-962d2c7833f9)

The only chance is to delete the SPI folder and re-load the complete content or just delete the old one. But this is not user-friendly.

I think the main problem is that Qirx does not use the original file names.

![grafik](https://github.com/softsyst/qirx_issues/assets/24510556/8001a2c2-9cd6-44d3-a31b-a4340a7acd1a)

# new logo
![8802B362](https://github.com/softsyst/qirx_issues/assets/24510556/d2b0e199-b3a5-412d-bb75-63aef5a23c44)

# old logo
![24742BB](https://github.com/softsyst/qirx_issues/assets/24510556/205e48d0-5419-46c7-a284-15ad2b0f7e1b)

# Download SPI folder

[E0A101.zip](https://github.com/softsyst/qirx_issues/files/12590778/E0A101.zip)

**Comment by softsyst** [comment]
I can confirm this behavior. The main problem is not the possible effort for the users, but the fact that the users will not get an information whether a logo changed.
Your zip is ok, but the more interesting one would have been the service directory in the SidPool_xy directory.

I will investigate the effort and consider it for one of the next versions. It should not happen too frequently though.
Anyway, thanks for this input. In the meantime, it should suffice to delete the folder of the affected service, also in the SidPool directory.

**Comment by softsyst** [comment]
Should be fixed in 4.1.3. However, I leave it open for some time, for a possible negative feedback.
