### ISSUE TITLE
Slider playing .raw

### ISSUE THREAD

**Issue by WIHDIA** [softsyst/qirx_issues#12]
Playing a .raw something annoys me a bit. You can move the slider to a different time frame when the recording is playing and **NOT** when it's in pauze. To me this is a bit counter-intuitive. 

73
Herman
[](https://wijnants.info/fmdx/)

**Comment by softsyst** [comment]
As useful as it would be, there are some technical difficulties in the realization. The request will stay open, it's just a matter of time and priorities.

**Comment by softsyst** [comment]
Hi Herman,
At last I found some time to solve this issue. Was a bit tricky. I'll send you a pre-release within the next days.

73,
Clem

**Comment by WIHDIA** [comment]
Super. Looking forward to checking out this pre-release.
