### ISSUE TITLE
Overload

### ISSUE THREAD

**Issue by superblyb** [softsyst/qirx_issues#123]
While the AGC is turned on and the LNA state set to 3, (only) for 12C NPO on my yagi antenna pointed to Roermond, Qirx is always and constantly warning for overload.
I assume it will not harm my device, and this would not be a bug, but I  wonder how I should deal with this warning.

![overload](https://github.com/softsyst/qirx_issues/assets/129985820/d7cc7ef3-64ea-4833-89f9-a5738c2f69ad)

**Comment by softsyst** [comment]
The overload indication means what it says. The iq data levels in the sdrplay device are too high, and the device reports overload. To get rid of this indication you need to lower the amplification of the LNA. This means you should increase the LNA state, i.e. shift the slider to the right. Unfortunately, sdrplay decided that higher LNA state numbers mean lower amplification.
The LNA State is not taken into account by the AGC (which works on the hardware), so - unfortunately - it must be adjusted manually.

**Comment by superblyb** [comment]
Should I adjust the LNA value when i am getting the overload message, or can I just leave the default LNA value and ignore the overload warning?

**Comment by softsyst** [comment]
If you are happy with the signal in an overload situation, you can leave it. But sometimes very strong signals drive the overload into a situation where it cannot be cleanly decoded any more. In this case you need to correct the overload.
No general rule applies. You might wish to experiment yourself.

**Comment by superblyb** [comment]
Ok, I will do so. Thx for answers.

**Comment by superblyb** [comment]
Usually the incoming reception is very strong when an overload message occurs. So that wouldn't be a problem. 
But could a overload situation be harmful for my device?

**Comment by softsyst** [comment]
In my opinion not. But you should ask this question to SDRplay. They are the manufacturers of the hardware.

**Comment by superblyb** [comment]
This also impacts on all other devices. When considering the default settings in Qirx, should an overload situation be avoided considering the electric stream through the devices' components?
P.S. i realise all other decices also are subject to the SDRplay functions too. But according to you, should the overload situation be avoided?

**Comment by softsyst** [comment]
There is a discussion in the [rundfunkforum](https://www.rundfunkforum.de/viewtopic.php?f=11&t=56472&p=1739447#p1739447) about this issue. It is in German, but Google can translate it for you.

**Comment by superblyb** [comment]
It seems since the new version V4.1.3 the overload message doesn't show up anymore (and neither does the non etsy phases message, as it seems to me).
Would just the messages have been left out?

**Comment by edd-cgfan** [comment]
Hi Clem,

Thank you for releasing a new version.
Just testing version 4.1.3 with my RSP2 and it looks like that everything works well except the overload indication:
I miss it. I think it is a very good feature. When it appeared one could quick and easily change the LNA state.
Would it be too much programming effort to make the visible indication selectable? 

Regards,
cgfan

**Comment by softsyst** [comment]
Thanks for your remarks. There is a new version uploaded which also repairs the missing Overload. I had commented it because it annoyed me in some experiments, and forgot to restore.

More important is that hopefully this new version works again also on computers without Avx support. 
@superblyb : The Non-ETSI indication worked here, no problem. If you think it is a problem, please open a new issue. But I can tell you already here, that also for such investigation I need a raw.

**Comment by edd-cgfan** [comment]
Thanks for the info: It's working well again.

Regards,
cgfan

**Comment by superblyb** [comment]
@softsyst : I noticed the non etsi messages are still there. And for a good reason I suppose. No need to tell I'm very happy with Qirx.

P.S.
For FM, it does help to reduce the gain on overload, this improves the signal.

**Comment by softsyst** [comment]
As the Overload indication is working again. I close this one.
