### ISSUE TITLE
Detection fails

### ISSUE THREAD

**Issue by superblyb** [softsyst/qirx_issues#124]
Sometimes, when tuning into a frequency, Qirx fails to detect the received signal. 
Afterwards, sometimes it takes some time up to maybe a minute, then the signal will come up.
But also, sometimes, the detection of the signal keeps failing while the incoming signal is strong. See the picture.
When this occurs, I can switch within Qirx to another antenna, then the signal will pop up, even if the signal strength is minor; and, then when I switch back to the first antenna, the detection will remain.
I noticed this behaviour also occurs with my fixed Philips receiver BTB8000 (a certain frequency is not coming through while the signal is more than strong enough).

![detection fails](https://github.com/softsyst/qirx_issues/assets/129985820/1ff39659-b501-4aaf-93b8-55a18cfd3391)

**Comment by softsyst** [comment]
To be able to comment, I would need a raw file of at least one minute.

**Comment by superblyb** [comment]
Will do, but I will have to wait for a new occurence.

**Comment by superblyb** [comment]
I recorded a raw file, but I'm not sure where to send the file. It is about 204 MB, I do have google drive, but I'm not so familiar with the sending proces. 
9C had a super strong incoming signal but the data wouldn't come up at all (not even after half an hour or so).
I'm storing the file on my google drive, but I am not sure how to share it next.

**Comment by superblyb** [comment]
https://drive.google.com/file/d/1_72MExQjv7GuH5tTDqc5lcrWSgahb6Xf/view?usp=sharing

**Comment by softsyst** [comment]
Ok, thanks Hans. I downloaded it and had a look.

If this is a really strong signal (as you state), then it looks hopelessly overloaded. Look at the Magnitude difference between the DAB (middle) part of the signal and the noise at the left and right corners. They are almost identical, as is typical for overloaded signals.
Try to reduce the LNA amplification of your RSPdx, i.e. increase the LNA number (shift slider to the right) and observe the spectrum. Your signal looks like so:
![image](https://github.com/softsyst/qirx_issues/assets/51386375/dff2ba24-b2d0-40d8-bf0a-d2a93d952cda)

A nice and strong signal should look similar like this:
![image](https://github.com/softsyst/qirx_issues/assets/51386375/74310a5e-1086-4f7e-bb89-6507bc0a725a)

Regards,

Clem

**Comment by superblyb** [comment]
@Clem: Right : I noticed afterwards that I had set my LNA to zero, which is of cause not good. However, this behaviour occured earlier to 11D Radio fuer NRW while the LNA was set to normal (=3), and while there was no overload.
So I wonder what would be the mechanism that causes Qirx not to show the usual data. The outcome is sort of blocked.

I wonder if it maybe has something to do with a high number of incoming sending locations.

P.S. The CNR value stated 40+ at a certain moment (but no further data about the programs and so on). The CNR value varied and disappeared.

**Comment by softsyst** [comment]
Maybe you can upload an example of such a reception. What you showed here was nothing special. LNA 0 is poison for strong signals.
I close this now as I do not consider it an issue for QIRX. But feel free to re-open if you think it to be necessary. But if so, then please provide an example showing the situation.
 
Thanks!

**Comment by superblyb** [comment]
Hi Clem,

I now have a valid example with a new raw file showing 11A VLAANDEREN1 from Belgium with a strong signal not being detected at all and under normal settings within Qirx : 

https://drive.google.com/file/d/1_72MExQjv7GuH5tTDqc5lcrWSgahb6Xf/view?usp=drive_link

**Comment by WIHDIA** [comment]
Hi Hans,
It says 9C over here and not 11A.


73
Kind regards
Met vriendelijke groeten

Herman Wijnants
My logblog
Belgium editor fmlist.org 

    Op maandag 11 december 2023 om 08:02:08 CET schreef Hans van Tulden ***@***.***>:  
 
 


Hi Clem,

I now have a valid example with a new raw file showing 11A VLAANDEREN1 from Belgium with a strong signal not being detected at all and under normal settings within Qirx :

https://drive.google.com/file/d/1_72MExQjv7GuH5tTDqc5lcrWSgahb6Xf/view?usp=drive_link

**Comment by softsyst** [comment]
Hi Hans,

sorry, I don't understand. The file of your link seems to be the identical file you already sent me two weeks ago.
Please check .

Regards,
Clem

**Comment by superblyb** [comment]
I recorded this raw file named 

2023_12_11_07_35_13_2048000_fHz216928000

on my google drive it is this link where I uploaded it today :

https://drive.google.com/file/d/1zcrDsa_Y5xRMG30zjbA8AxyWJAXTxNVJ/view?usp=drive_link

I might have posted a wrong link if the upload hadn't finished completely and I didn't notice.
Please check the above link again.

I will look again if I have anything done wrong on my google drive.

P.S. should I add an (your) adress to share with? If yes what is the adress?

**Comment by softsyst** [comment]
Doesnt't work, sorry. Google Drive reports "Access Denied". I clicked the "Zugriffsanfrage" (Rquest) button, and am now waiting for an email that the download request has been granted, according to Goggle. :(

**Comment by superblyb** [comment]
I confirmed your adress.

Op ma 11 dec 2023 om 17:01 schreef softsyst ***@***.***>:

**Comment by softsyst** [comment]
Ok, the download worked. Thanks for this.

This is indeed a strong signal which is not synchronized by the 4.1.3. Therefore, I re-opened this issue.

I had a quick look into the code: A small, but obviously essential timely difference in the sync algorithm was too narrow.
The signal seems to be received at almost identical strengths from two different transmitters, and this fact resulted in the mentioned difference as to be too narrow.

After widening it a little bit, the result is like so:
![image](https://github.com/softsyst/qirx_issues/assets/51386375/75749053-47f0-425a-966e-ff1158c3956a)

After that little change, everything looks fine.
Again, thanks for this input!

**Comment by superblyb** [comment]
In einem neuen Szenario, bei dem 11D Mein NRW DAB+ ausgewählt war, hörte ich 1LIVE. Dann brach das Audiosignal ab, nachdem ich meinen Webbrowser zum Surfen geöffnet hatte. Bei Qirx führt ein Wechsel der LED-Bildschirmaktivität normalerweise dazu, dass das Signal kurz ausfällt, um dann schnell wieder zurückzukehren. 
Aber in diesem Fall blieb das Audiosignal weg, ebenso wie andere Funktionen. Der Eintrag in der Kanalliste blieb intakt. Der CNR-Indikator zeigt einen negativen Wert von -8,4 an und der Wasserfall bewegt sich weiter (siehe Screenshot).  Auch das Umschalten von Antenne A auf Antenne B bei meinem RSPdx führte nicht zu einer Rückkehr des Signals, wie es normalerweise der Fall wäre.

![11D](https://github.com/softsyst/qirx_issues/assets/129985820/928fda7c-7ca1-4a9f-b248-2b9094746ca6)

Davon habe ich eine einminütige RAW-Aufnahme gemacht.

https://drive.google.com/file/d/1jwRxj-Ps4zdFb2l0ArRkSIu6POgtx5ui/view?usp=sharing

**Comment by softsyst** [comment]
In diesem Fall nützt die Raw Datei nichts, da die Störung nicht im Eingangsdatenfluss auftritt, sondern im DAB Teil. Hier spielt diese Datei ohne Unterbrechung, problemlos.

Wenn die Synchronisation nicht zurückkommt wie hier, hilft nur, den Rx zu stoppen und wieder zu starten. Solche Situationen sind sehr schwer zu lokalisieren, da sie nicht reproduzierbar sind. Mehr kann ich dazu leider nicht beitragen.
Insbesondere wenn Musikaufnahmen gemacht werden sollen, ist gleicheitiges Webbrowsing eine ganz schlechte Idee. Besonders das Scrolling im Browser macht Probleme. Ich habe schon stundenlange Aufnahmen ohne Unterbrechung gemacht, allerdings in dieser Zeit den Browser nicht angefasst.

**Comment by superblyb** [comment]
Today I made a screenshot of another occurence where the detection of 11D after one minute still failed. No signal was detected but when I changed to another antenna the signal came back as usual. The first antenna should have picked up the signal as well. 
I also made a raw recording on my hard disk.

![11D](https://github.com/softsyst/qirx_issues/assets/129985820/3ccbe549-e534-4961-be52-a73b0205f7fc)

Greetings and happy holidays.

**Comment by softsyst** [comment]
Please check in 4.2.1

**Comment by superblyb** [comment]
Thanks for the new version ! I guess this issue can be closed now.

**Comment by softsyst** [comment]
Thanks for feedback, Hans, and for cooperation!
