### ISSUE TITLE
Adding DAB-channel to the filename of an IQ-recording

### ISSUE THREAD

**Issue by Drehrumbum** [softsyst/qirx_issues#127]
I don't know how others feel, but even after years I don't know the DAB frequencies and the associated channels. And yes, Santa never asked me that... ;) Would it be possible to add the channel name so that it also appears in the filename of an IQ-recording?

Example:
Old: 2023_12_25_17_41_18_2048000_fHz220352000.raw
New: 2023_12_25_17_41_18_2048000_11C_fHz220352000.raw

QIRX v4.13 can handle such a filename regardless of whether the IQ recording contains an XML header or not. The frequency axis in the Speci window shows the correct center frequency and the right channel name is also shown in the drop down box on the left.

TIA Heiko
Merry Christmas to you all!

**Comment by softsyst** [comment]
Realized in 4.2.1

**Comment by softsyst** [comment]
No further feedback: I close it.
