### ISSUE TITLE
4.2.1 suggestion

### ISSUE THREAD

**Issue by WIHDIA** [softsyst/qirx_issues#129]
Hi Clem,

I love the DB Browser and I wonder if
1. the update button could also be activated by hitting the Enter key on the keyboard
2. the Country dropdown could also have an empty setting like the * or -1 settings. That would make it possible to do more powerful searches, but the results might perhaps be too much to handle for QIRX. 

This new DB Browser reminds me of this project: https://dxing.fi/log/

73

Herman
[My logblog](https://wijnants.info/fmdx/)
Belgium editor of [fmlist.org](https://www.fmlist.org/)

**Comment by softsyst** [comment]
Hi Herman,

**Suggestion 1**: Should be no problem.

**Suggestion 2**: You are right, one problem could be the performance. Another consideration was the non-uniqueness of the EId. It is unique only in combination with the ECC (extended country code), which is not contained in the database.

73,
Clem

**Comment by WIHDIA** [comment]
Hi Clem,

Some more suggestions about the new DB browser, which I find to be very useful and very easy to use.

1. What are the ? in the picture?
2. Would it be possible to add a Block dropdown with a wildcard? This should/could overrule all other dropdows and searches.
   Also the Search Fields are great, but wouldn't it be nice if they are separated with a AND/OR choice?  
   So Block 7D, Country NL and Eys or Ensemble Brab/ AND Site Name Eys would only produce 1 find. 
   Too far fetched?
   
   
![QIRX421E_05012024](https://github.com/softsyst/qirx_issues/assets/53539654/6f5a4893-e814-4f68-a320-c02d5fa008e4)

73

Herman
[My logblog](https://wijnants.info/fmdx/)
Belgium editor of [fmlist.org](https://www.fmlist.org/)

**Comment by softsyst** [comment]
**Ad 1**: The questionmarks are non-printable characters, in this case the small ° of degrees. They are still correct in the imported .csv file, but no longer in the generated Excel file. I have no solution, as the other characters in CZ (for the Name column) are ok.
Currently, I will not investigate on this.

**Ad2**: There are many more possibilities thinkable, exactly all combinations of all columns of the database. For the time being, I will leave it as is. However, I will collect suggestions and perhaps realize the most popular ones. All of this can of course be done, but the more combinations and wildcards, the more SQL queries (technically spoken) you need. This rather quickly becomes unfeasible, and one needs a more general solution which would be much more effort. And - to be honest - I do not see the big advantage of all these possible combinations.

73,
Clem

**Comment by WIHDIA** [comment]
Hi Clem,

Thanks for the feedback. Good idea to collect suggestions and then see what is the best way to proceed.

73

Herman
[My logblog](https://wijnants.info/fmdx/)
Belgium editor of [fmlist.org](https://www.fmlist.org/)

**Comment by WIHDIA** [comment]
Hi Clem,

More suggestions/requests.

1. Is there a way to limit the number of countries in the Country dropdown? I cannot find a way to do so in the config.
It would limit the scrolling down a bit. At my location I have no real need for IND or AUS although it's nice to pull them up.
2. Perhaps an alternative for 1 is to have a few favourite country buttons to be set up by the user.

Just my 2 cents :-)

73

Herman
[My logblog](https://wijnants.info/fmdx/)
Belgium editor of [fmlist.org](https://www.fmlist.org/)

**Comment by softsyst** [comment]
Hi Herman,

Limiting the number of countries would mean some kind of country multi-selector. This has to be maintained (persisted), and there has to be a possibility to reset the list. Currently, I would not like to spend this effort. Such a feature is much more work than a simple drop-down control. But as it certainly would be useful, I would not generally exclude it.
Not the least problem would be how to bring it reasonable on the surface.
The database does not feature a limiting attribute (something like "Europe" or "Asia"), thus a general selector would be needed.

A similar feature is provided for the DAB blocks, operated in the scanner. Personally, I use it only very rarely.

However, I thought about the "Block" drop down you had suggested. This might be something really useful. I hope to incorporate this in the next version.

73,
Clem

**Comment by WIHDIA** [comment]
Hi Clem,
Thanks for the feedback. Incorporating a Block dropdown in the next version would be great. Many thanks.

73
Kind regards
Met vriendelijke groeten

Herman Wijnants
My logblog
Belgium editor fmlist.org 

    Op zaterdag 20 januari 2024 om 20:00:06 CET schreef softsyst ***@***.***>:  
 
 


Hi Herman,

Limiting the number of countries would mean some kind of country multi-selector. This has to be maintained (persisted), and there has to be a possibility to reset the list. Currently, I would not like to spend this effort. Such a feature is much more work than a simple drop-down control. But as it certainly would be useful, I would not generally exclude it.
Not the least problem would be how to bring it reasonable on the surface.
The database does not feature a limiting attribute (something like "Europe" or "Asia"), thus a general selector would be needed.

A similar feature is provided for the DAB blocks, operated in the scanner. Personally, I use it only very rarely.

However, I thought about the "Block" drop down you had suggested. This might be something really useful. I hope to incorporate this in the next version.

73,
Clem

**Comment by softsyst** [comment]
Block dropdown is in 4.2.2. I close this one.
