### ISSUE TITLE
Request: resizing the DAB scanner window

### ISSUE THREAD

**Issue by WIHDIA** [softsyst/qirx_issues#13]
Resizing the DAB scanner window would be handy so as to have a complete overview of all scanned muxes when there are many.
No scrollbar needed then.

**Comment by softsyst** [comment]
Thanks for the suggestion, Herman. I'll have a look and estimate the effort. But I'm afraid the scrollbar will remain necessary, with your antenna situation....

Clem

**Comment by softsyst** [comment]
I checked it and it is more work than expected. Thus, postponed.

**Comment by softsyst** [comment]
It will come in 4.03

**Comment by softsyst** [comment]
Realized in 4.03.
