### ISSUE TITLE
Content of SPI folder for EID E01135

### ISSUE THREAD

**Issue by edd-cgfan** [softsyst/qirx_issues#131]
Hi Clem,

Because of rebuilding the SPI folder with version 4.2.1 I found additional content in the folder for E01135, i.g. MDR S-ANHALT mux on 6B. There are folders for 5C as far as I can see.
Here is the zipped SPI folder:
[V421_SPI_.ZIP](https://github.com/softsyst/qirx_issues/files/13847449/V421_SPI_.ZIP)

Additionally, there are 2 logos lost:
![6B-SPI-Lost_mdr-kult_V421_](https://github.com/softsyst/qirx_issues/assets/49753409/ef2b5ff2-b98d-4b43-b9c1-8a74b2cd9ead)

MDR KULTUR  SID=D3C3
For MDR S-ANHALT EXT  SID=D8D1 I'm not shure if I put it there myself sometime in the past.
Here are the images from the old SPI folder:
[E01135_D3C3.ZIP](https://github.com/softsyst/qirx_issues/files/13847479/E01135_D3C3.ZIP)
[E01135_D8D1.ZIP](https://github.com/softsyst/qirx_issues/files/13847480/E01135_D8D1.ZIP)

Strange thing too: The SPI information is completed in less than 66 seconds, when I watched the green LED indicator.
I don't see any content in the temp folder.

How long should a raw file be for further investigation?

Regards,
cgfan

**Comment by softsyst** [comment]
To evaluate the green lamp properly, you need to restart the app. After restart and having selected the mux, the lamp blinks until all is collected. After a successful collection and e.g. only a stop of the receiver or having in between selected another mux, the lamp usually stops quickly. This is the case when the SPI transport id had not changed. With the same transport id, the sent info is identical. The SPI time can drastically vary in the different muxes, there is no rule. I have seen times between one minute and 30 minutes.
To evaluate a raw file, the SPI must have been received completely.

Regards,
Clem

**Comment by edd-cgfan** [comment]
Today I tried to reproduce the additional occurrence of folders for the 5C in the E01135 folder but without success:
The folders have not been updated:
[6B_MDR_SPI_E01135.ZIP](https://github.com/softsyst/qirx_issues/files/13850886/6B_MDR_SPI_E01135.ZIP)

Keeping your explanation in mind I was playing around. However, I only can see that the SPI indicator lamp stops moving after around 65 seconds.
By chance I was able to see and copy parts of the SPI temp folder:
One image for MDR KULTUR SID=D3C3 is in this folder.
[6B_MDR_SPI_Temp_668fc2fe-3bd9-4f81-89cb-41abf50c4ad4.zip](https://github.com/softsyst/qirx_issues/files/13850877/6B_MDR_SPI_Temp_668fc2fe-3bd9-4f81-89cb-41abf50c4ad4.zip)

What I noticed too is that the EPG for MDR KULTUR is not shown. I saw that earlier (at least with V4.1.3) but I didn't think about it, because MDR KULTUR and KLASSIK often have the same content.
It looks like that there is EPG information when looking into the .EHB files .

Here is the link to a 10 minute raw file for your convenience:
[2024_01_06_18_53_41_2048000_6B_fHz183648000.raw](https://drive.google.com/file/d/1Bl_gF6M2yx8BzLzDhmbTF7q_kt8RvaL4/view?usp=sharing)

Regards,
cgfan

**Comment by softsyst** [comment]
Thanks very much for the 10-minutes file. I will inspect it, together with the rest of your info.

**Comment by softsyst** [comment]
After some research with your raw file, here are the results (spoiler - QIRX seems to do everything correctly):

1. The collection time is indeed very short. After the lamp stops everything has been collected.
2. Attached you find two files in the zip: The originally sent .EIB file, in case you want to control the - also attached - .eib.xml file, which has been created for easier processing by qirx. The numbers of the filename are the transport Id's of the collection.
3. Please have a look inside this xml file, I always do it with "XML Notepad".  You find the service metadata for all services. 
     Now please open the nodes "service/bearer". If you do it for all services, you will find that the service entry for SId D8D1 is completely missing, 
    and the "bearer" entry for "MDR KULTUR" is missing as well, meaning that the SW cannot match the picture to the Service.

If you want  to control it yourself, you could go through the binary file and inspect it byte by byte. If you want to do it, please tell me, and I will guide you to the ETSI standards covering the meaning of the entries.

That's all, so I am pretty sure that qirx is doing everything correctly, at least here. 
Same procedure as last year with DLF, ...
[40889_40810.EIB.zip](https://github.com/softsyst/qirx_issues/files/13851647/40889_40810.EIB.zip)

Regards,
Clem

**Comment by edd-cgfan** [comment]
Many thanks Clem for the investigation and the detailed explanation.
Yes, I was able to see the content of the xml file.
It must have worked at some point in the past, because the corresponding folders are available in the "old" SPI directory. 

> That's all, so I am pretty sure that qirx is doing everything correctly, at least here.

I had expected that.

> Same procedure as last year with DLF

I'll drop them a line or two...

Regards,
cgfan

**Comment by softsyst** [comment]
Thanks for feedback. Let's see if you get an answer.. I close it now, in case something to be investigated further should show up, please feel free to re-open the issue.

Thanks and Regards,
Clem
