### ISSUE TITLE
similar sub-value entries

### ISSUE THREAD

**Issue by superblyb** [softsyst/qirx_issues#132]
Would it be possible to show similar sub value entries for a given country in the DB browser, so that you can foresee possible tii collisions on the map?

**Comment by softsyst** [comment]
This is possible already, but only for a given SubId, meaning you should know the Sub Id which you are interested in.

Selecting the SubId of interest and wildcards for EId and MainId gives you some results (after clicking "Update",  of course). Now, select those results with same EId and same block, and you have the colliding muxes on the map.
If you know the EId beforehand, of course you can select it as an additional filter, to exclude results which are not of interest.
The pictures show an example for NL, EId NPO (8001), Sub Id of 10:
![image](https://github.com/softsyst/qirx_issues/assets/51386375/3391aade-e8ae-4c00-a719-72767e4c8781)
and the map, with a possible Rx:
![image](https://github.com/softsyst/qirx_issues/assets/51386375/6b2180ef-e60c-4542-ade4-daa64a2e3b0f)

**Comment by superblyb** [comment]
Thanks for answering. 
This is a nice enhancement. I figured out -1 stands for a wildcard just as the * . 
I am still learning how to play with this new enhancement.

I was furthermore thinking in a somewhat different direction.

I can receive here from Germany : 5C, 9B, 9D and 11D. I would like to see on the map all stations from these blocks, which have the same sub-ID, and provided with the usual tag on the map.
Could this perhaps also be possible in the future?

P.S. by stations I mean transmitting sites.

**Comment by softsyst** [comment]
Why would you need the same sub Ids from different blocks? different blocks mean different frequencies, so they will not contribute to TII collisions. TII collisions come from the same block, same EId, same SubId, different Main Id.
Technically, a selective filter for more than one block would be a considerable effort, On the GUI (some kind of multiselection, which is not provided "out of the developers GUI toolbox") as well as from the database query.
This said, to answer your question, I would hesitate (however not generally reject currently) to implement your request, if I see not strong arguments in favor of it.

**Comment by superblyb** [comment]
I did not realise that tii collisions cannot be the result of similar sub values from more than 1 block. Therefore, I withdraw my current request.
Thank you again for your explanation.

**Comment by softsyst** [comment]
You are welcome. I think I can close this thread now.
