### ISSUE TITLE
Observations using the DB Browser

### ISSUE THREAD

**Issue by edd-cgfan** [softsyst/qirx_issues#133]
Hi Clem,

I like the DB Browser too and encountered this behavior yesterday and could reproduce it today:
QIRX receives the multiplex on 5C.
With the DB Browser I wanted to let show the 10B transmitters for Berlin/Brandenburg on the map.
With my eastbound antenna I also get the 5C signal from the transmitter in Belzig that also has the 10B:
Everything looks fine on the map:
![5C+DB-Browser+10B](https://github.com/softsyst/qirx_issues/assets/49753409/aec25b3d-dcd1-4e4a-90d7-032ea2ecf92a)

Then I switched off displaying the 10Bs. It happens that also the 5C from Belzig is removed from the map:
![5C+DB-Browser-not-10B_](https://github.com/softsyst/qirx_issues/assets/49753409/ce0c7c89-9e08-4e92-b399-a36a761ee7e7)

I then tried to get it back again on the map but without luck:
First I checked "Show all entries for this EID on the map".
Then I searched and checked all entries or only the one for Belzig from DR Deutschland in the DB Browser.
The 5C Belzig remained invisible as shown here:
![5C+DB-Browser-Belzig-doesent-come-back](https://github.com/softsyst/qirx_issues/assets/49753409/4eb6e312-5ac6-40ed-848f-4704a193c2df)

Additional observation today because of tropo conditions: 5C from Petkus is received (blue circle).
5C and 10B from Petkus are removed too but 5C appears again because the strength varies while the strength of Belzig is almost stable.

Here is the link to a 5 minutes raw file of the 5C in order you would like to reproduce it:
[2024_01_09_18_23_04_2048000_5C_fHz178352000.raw](https://drive.google.com/file/d/1gFfTwmBY8anAnQ0XMTR3ZydJ3BCmyEKg/view?usp=sharing)

Regards,
cgfan

**Comment by softsyst** [comment]
Hi cgfan,

Sorry for my late response. Thanks for your file. I hope I could isolate the error and fix it. Maybe you could have a look before I publish it. I send you a PM.

Thanks!
Clem

**Comment by softsyst** [comment]
Fixed in 4.2.2
