### ISSUE TITLE
Parameters when calling the console

### ISSUE THREAD

**Issue by bi3mw** [softsyst/qirx_issues#134]
Hello,
first of all, thanks for the useful Linux console. It would be nice if you could pass the parameters directly to the command line when calling the program. Like this:

./qirxConsole -start=2 -demod=DAB -ens=5D

**Comment by softsyst** [comment]
Hi bi3mw,

Thanks for this input. This exists (almost) in the way you describe it. Not published though (shame on me...). Such a script is e.g.

#!/bin/bash
xterm -e "./rtl_tcp -d 0 -a 127.0.0.1 -p 1234" &
xterm -e ./qirx_audio/qirx_audio &
xterm -e ./qirxConsole 	qirxConsole -start=1 -demod=DAB -ens=5C &


It starts the I/Q data server, here rtl_tcp, the qirx_audio (necessary for DAB) and the qirx. The second "qirxConsole" is necessary and denotes the base of the data directory tree. The rest is exactly as you request it.
These scripts do not only work for DAB, but also for other demodulators, like AM (Airband) or WFM.

I attach a zip file containing the scripts I have tested on Debian11. Please check it out.

Regards,
Clem


[startMeScripts.zip](https://github.com/softsyst/qirx_issues/files/13953403/startMeScripts.zip)

**Comment by bi3mw** [comment]
Thanks for the quick feedback. It works almost perfectly. There is only a problem when entering the ensemble. The output is the following: 

Processing command: ens=5D
Creating Ensemble 5D 
DAB Synced after 2 seconds
Block: 5D, Name: , EId: 0
Available Services:
(0) None

But if you enter "ens=5D" manually afterwards, the list of channels appears correctly. Perhaps a delay is necessary.

**Comment by softsyst** [comment]
You might repeat the ens command. Sometimes it needs some time to sync. With EId=0 the ensemble is  of course not yet completely synced.

**Comment by softsyst** [comment]
No more actions on this one. I close it. If you think it requires action, please feel free to re-open.
