### ISSUE TITLE
Qirx on a Mac?

### ISSUE THREAD

**Issue by superblyb** [softsyst/qirx_issues#136]
I don't know if this has come up before, but is there the possibility of Qirx working on Mac Os in the future? And I don't mean with homebrew or anything like that, but as an app for mac os.

**Comment by softsyst** [comment]
No. The QIRX GUI technology is WPF (Windows Presentation Foundation), which - currently - only works on Windows. Multi-platform GUI Apps usually work with Qt. 
I have no information whether MS has plans to provide WPF also for Linux and/or MacOS.
The .NET technology used by QIRX also works on Linux (MacOS is a "Unix-like" OS), and a Linux version of QIRX exists as a result, but without GUI, as a Console version. No MacOS version though.

**Comment by superblyb** [comment]
So far I use 2 times a Windows os because of Qirx. Qirx is the only reason I use Windows so far. 
But I am not complaining because I'm very happy with Qirx on Windows.

**Comment by softsyst** [comment]
Nothing more to contribute from my side. I close this one.
