### ISSUE TITLE
Opening Tll Logfile

### ISSUE THREAD

**Issue by Frank-56** [softsyst/qirx_issues#137]
When I click on "View newest TlI Logfile" Qirx opens the file with the Windows Editor although the file extension .txt is associated with another editor like notepad++ or Ultraedit. Qirx should open the editor associated with the extension.

**Comment by softsyst** [comment]
QIRX is using the editor which is stored in the config file, tag Paths/Editor. Default entry is notepad.exe. Feel free to manually edit this entry.

**Comment by Frank-56** [comment]
Seriously? Editing an xml-file deep down in Appdata? This is not something that Redmond feels good with. Same as for muting applies: no good design. You can close this one, too.

**Comment by softsyst** [comment]
No further comments, I close this one, as suggested
