### ISSUE TITLE
Qirx connection fail

### ISSUE THREAD

**Issue by superblyb** [softsyst/qirx_issues#141]
After I updated to the newest SDRuno version, I am getting this error message "Qirx connection fail" and Qirx refuses to start.
This only occurs with my RSP device and not with my RTL-SDR device.

**Comment by superblyb** [comment]
After reinstalling Qirx and reset some settings, the problem seem to have disappeared on its own. Perhaps Clem could comment on possible causes. Are there any implications for updating SDRplay/SDR/uno?

**Comment by softsyst** [comment]
There should not be the necessity for a re-install of QIRX. 

Maybe it is a problem (which I here see also occasionally) with the Service necessary by the RSP hardware. This Service sometimes (very rarely) seems to stop. You can control it like so, on Win10:

Right click on the "Windows" Icon in the lower left corner of the screen, select "Computer Management", then "Services and Applications, then in the right pane "Services". The "Computer Management" Console shows you a list of all Services.

![image](https://github.com/softsyst/qirx_issues/assets/51386375/e6674fca-6462-4186-b65d-d18e89ac33d3)

Check the content in the green marked line "SDRplay API Service". It must be "Running". If not, you can try to start it by a context menu (right mouse) and select "Start". If that Service is not running, the RSP3_tcp will not be able to access the RSP hardware. RSP3_tcp makes no attempt to start the Service (what SDRUno perhaps does).

SDRUno and QIRX both use that Service. It is installed by the SDRplay software. The SDRUno installer probably re-installs that Service.

In the error case, you could have checked the RSP3_tcp console window and inspect its output. If it was a "Service" problem, you should have seen some related error message.

This Service was introduced some time ago by sdrplay and allows applications to access the RSP hardware at the same time, e.g. SDRUno should run simultaneously with QIRX, if you have more than one RSP device connected. Likewise, you could have two RSP devices run by two different receivers within the same QIRX instance.

**Comment by superblyb** [comment]
I understand that the SDRuno update does not affect the functioning of Qirx. Therefore the errors must have been occasional.

**Comment by softsyst** [comment]
You are right, but if you run both at the same time, you need two RSP hardware devices.

**Comment by superblyb** [comment]
I have 2 RSP devices :)
Thx for your time, I will close this now.
