### ISSUE TITLE
RSPdx and choosing antenna A, B or C

### ISSUE THREAD

**Issue by WIHDIA** [softsyst/qirx_issues#142]
Hi Clem,

I've just acquired a RSPdx and it works well with QIRX. Unfortunately after closing down QIRX its default antenna setting becomes A.
As I use a LNA (biasT) my default antenna is B (it has biasT, unlike A and C).
It would be nice if QIRX remembered my antenna preference. 

73

Herman
[My logblog](https://wijnants.info/fmdx/)
Belgium editor of [fmlist.org](https://www.fmlist.org/)

**Comment by softsyst** [comment]
Thanks, Herman, for this very useful suggestion!

73,
Clem

**Comment by softsyst** [comment]
Realized in 4.2.2
