### ISSUE TITLE
Feature suggestion: MOT Slides Analyzer for DAB

### ISSUE THREAD

**Issue by salvaaod** [softsyst/qirx_issues#145]
There is one feature that I will love to see in QIRX, audio and PAD slide análisis DabPlayer from Andreas Gsinn does, it,  the feature is the capability to analyze actual audio bitrate and PAD, being able to see the size of MOT (silide) downloaded and graphics, Below is a photo of the PAD analyzer, you can see the total channel Bitrate, the Slide Bitrate and size downloaded, and the audio bitrate.

Thanks for your consideration.

![image](https://github.com/softsyst/qirx_issues/assets/26838980/64ab4f60-dd7b-4def-a293-ba79a1786df6)

![image](https://github.com/softsyst/qirx_issues/assets/26838980/4bc68d56-81bb-4f23-8c26-d2b7fe194953)

**Comment by softsyst** [comment]
Thanks for your input. I will make an estimate for the effort and decide accordingly. Most of it seems useful to me, what I will probably omit is the numbers above the progress bar, which would influence the GUI design of the "Service" tab. A progress bar is already provided.

**Comment by salvaaod** [comment]
Actually the data that it will be desired will be:
*Service Bitrate (already provided)
*Actual Audio Bitrate
*PAD Bitrate
*Slide size being downloaded
*% and data downloaded of the current slide.

The Audio bitrate and PAD Bitrate will have to have into account the RS overhead.  This will give a detail about the actual audio quality and PAD overhead.

BR.

**Comment by softsyst** [comment]
After a look into the efforts, also considering possible GUI drawbacks, I suggest the following enhancements:

- Service Bitrates, pre Viterbi and after Viterbi (the latter should coincide with the nominal bitrate),
- Bitrates of the AAC data incl. XPad of the stream going to the AAC decoder
- Bitrates of the XPad
- PCM Audio Samples rate returned by the AAC decoder

What will not be implemented is the % and data of the download rate, and slide sizes. The pictures can be stored, and the % of the download rate can well be estimated from the progress bar.

**Comment by salvaaod** [comment]
Thanks Clem, I think this will be a great feature.

**Comment by softsyst** [comment]
Implemented in 4.2.2
