### ISSUE TITLE
RSpdx and RSP1A Blocked Band

### ISSUE THREAD

**Issue by WIHDIA** [softsyst/qirx_issues#146]
Hi Clem,

As mentioned in #142 it would be great if the Antenna choice with RSPdx is retained, but retaining the 'Blocked Band' 
with RSPdx and RSP1A would also be a nice feature.

73

Herman
[My logblog](https://wijnants.info/fmdx/)
Belgium editor of [fmlist.org](https://www.fmlist.org/)

**Comment by softsyst** [comment]
Implemented in 4.2.2
