### ISSUE TITLE
4.2.1 Stereo shows as Mono

### ISSUE THREAD

**Issue by jpuigs** [softsyst/qirx_issues#148]
![image](https://github.com/softsyst/qirx_issues/assets/44906458/93e823f2-86a7-44ca-9b31-ece186c7faba)

Service has stereo sound, Parametric stereo is active, and  Mono/Stereo shows Mono ?!?

**Comment by softsyst** [comment]
Sorry, my crystal ball is just out of service. A friendly remark for you: Such entries are ignored if they do not provide some more info. The least is a raw file of at least one minute, together with a download link posted here,

Thanks for consideration.

**Comment by jpuigs** [comment]
OK, I thought that watching the attached picture was enough when reading these two contradictory values...
Mono / Stereo = Mono
Parametric Stereo = Yes

Here you have 1 minute recording.
https://we.tl/t-2g8g5qbifW
Affected services are all of them, note that some services still don't work,

**Comment by softsyst** [comment]
Thanks for your immediate feedback and the raw. Everything looks ok. It is a Stereo audio, encoded as Parametric Stereo. 

Wikipedia writes:
"**Parametric Stereo digitally codes a stereo audio signal by storing the audio as monaural** alongside a small amount of extra information"

The AAC encoder creates from the stereo input a mono signal, which QIRX correctly indicates as such. The AAC decoder (libfaad, in QIRX residing in the separare exe called qirx_audio) re-creates the Stereo. If you look at the "Audio" tab you will see that the audio decoder created Stereo:

![image](https://github.com/softsyst/qirx_issues/assets/51386375/7176a119-90d9-4e62-bbf4-5c34697d0a88)

Apart from this, the SId's of the services seem to be not conforming to the Standard ETSI TS 101 756 V2.4.1 (2020-08). The upper four bits should be 0xF, for France (together with the correct ECC of E1), not 1, 8, B, D, or E. See Table 3 in that document.

**Comment by jpuigs** [comment]
Ok, understood. I know what is a parametric stereo signal.
It would be comparable to FM MPX signal. A main Mono audio + stereo data (L-R) in a subcarrier.

SIDs are like boleean lottery.......   It's a Spanish (Pirate) MUX......

**Comment by softsyst** [comment]
I already wondered about the Spanish soundtracks...

**Comment by softsyst** [comment]
Item has been clarified. I close it.
