### ISSUE TITLE
Request: video

### ISSUE THREAD

**Issue by WIHDIA** [softsyst/qirx_issues#15]
I often make videos of raw recordings/live sessions using Flashback recorder (or any other alternative).
Wouldn't it be cool to have a built-in video recorder as e.g. is available in SDRConsole (Simon Brown's excellent package).
The built-in audio recorder is excellent.

**Comment by softsyst** [comment]
Similar like the screenshot suggestion.
Win10 provides an excellent built-in possibility to do it. Just press the Windows key +G, and you will get what you want. It works very good. Just don't be confused by having to tick "Yes, this is a game". You will even get sound if you like. Did it many times.
I suggest to close this one.

**Comment by WIHDIA** [comment]
OK. Always comparing to SDRC :-)
