### ISSUE TITLE
RSP3_tcp issue with new SDRPlay RSP API v3.15 installed.

### ISSUE THREAD

**Issue by MW0CDO** [softsyst/qirx_issues#153]
Hello Clem.

Since SDRPlay dev team released SDRConnect Preview 3 along with a new API v3.15, QIRX now cannot access the stream.
The error message is:

Error Starting IQ data server RSP3_tcp
Please check your configuration or your TCP/IP connection!

Everything was fine until the installation of the preview, so I'm certain it is not configuration or TCP/IP settings.

I asked Andy, one of the SDRConnect developers and he very kindly investigated and I paste his comments & findings below for you.

[Andy Play] just as a follow up, I just rebuilt rsp3_tcp myself and all I did was change the Visual Studio project properties to point to the installed API 3.15 instead of the included API 3.10, built it and it started and found my RSPdx - now that was just a quick test, I won't redistribute this because I don't know what this is doing and then I'd have to support it, but I just wanted to show what the issue was.

I know it's a 'cheeky request', but could you please rebuild RSP3_tcp as Andy says above?

Many thanks!

**Comment by softsyst** [comment]
Thanks for this input. I hadn't followed the new versions recently. I hope it won't be a big issue. What is also still pending in this respect, is the inclusion of the RSP1B identification. Will check also the 3.15 API whether it contains new features.

Clem

**Comment by softsyst** [comment]
Just released the RSP3_tcp V0.3.11 to GitHub. 
It works with the SDRplay API 3.15. The device range includes the new RSP1B and the RSPdxR2.

The binary RSP3_tcp.exe can be found in the RSP3_tcp GitHub repository under
`RSP3_tcp/x64/Release`

The Debug version can be built according to the instructions there.

Tested on Win11.

For use with current QIRX 4.2.2, just copy the RSP3_tcp.exe together with the sdrplay_api.dll into your QIRX install directory.

Before you start with this, make sure that you are running the V3.15 of SDRplay's service. Check in Win under 
ComputerManagement -> Services and Applications -> Services -> SDRplay API Service (v3.15).
The sdrplay_api.dll unfortunately shows no version number in Win Explorer.

**Comment by MW0CDO** [comment]
Many thanks Clem!

Paul.

**Comment by softsyst** [comment]
I close this.
