### ISSUE TITLE
qirx crash at startup

### ISSUE THREAD

**Issue by nona00** [softsyst/qirx_issues#161]
Updated qirx from 4.21 to 4.23.

Application crashes at startup:

![grafik](https://github.com/user-attachments/assets/6c900817-4389-44bf-ae94-92d964c58e2d)

win 10 prof 22H2

windowsdesktop-runtime-8.0.8-win-x64 is installed

**Comment by nona00** [comment]
it was an issue with the old 3.2.2 version.

de-installation of 4.2.3, installation of 3.2.3 and then 4.2.3 solved the issue

**Comment by softsyst** [comment]
How can I reproduce it? Some more info would be good. I have here 3.2.3 not installed, and do not have crashes on startup.

**Comment by nona00** [comment]
I can reproduce the issue again. After I used 4.2.3, 3.2.3 can no longer be started, the old versions crashs at startup:

![grafik](https://github.com/user-attachments/assets/38f55fa4-0ff8-4ed6-b94e-7bf6b8860029)

**Comment by softsyst** [comment]
Ok, but how can I reproduce the issue. What do I have to do?

**Comment by nona00** [comment]
can be closed, on windows 11 when 4.2.3 is installed 3.2.3 is removed. I will manually remove 3.2.3 on windows 10 and use only 4.2.3
