### ISSUE TITLE
Suggestion: Showing the frequency of the pilot tone in the MPX spectrum

### ISSUE THREAD

**Issue by Drehrumbum** [softsyst/qirx_issues#163]
Hi Clem!

Recently, in a completely different context, I remembered an old thread that I have now found again in the German-language 'rundfunkforum'. This thread from 2007 is about the highly precise determination of the frequency of the pilot tone in the MPX signal of commercial FM transmitters in order to determine whether several transmitters are broadcasting the same MPX signal (e.g. ball reception) or whether the audio signal is being sent from the broadcast studio to the individual transmitters and the MPX signal is generated there. 

https://www.rundfunkforum.de/viewtopic.php?f=4&t=18648

I think, this is still interesting stuff, because today we have the 'Bundesmux' on DAB+ as a nationwide GPS-controlled frequency standard, highly stable TCXO quartz crystals in the SDR dongles and the possibility of calibrating a wide variety of dongles quite precisely using the DAB signal and QIRX.  

What do you think about it?
How accurately can we measure? (<1mHz would be nice) 
Would the measurements (two dongles previously calibrated via DAB on two different computers measuring the same station) be comparable?

BFN Heiko

![pilot_of _the_airwaves](https://github.com/user-attachments/assets/83765ac1-c2f4-4393-adad-72498f13c08b)

**Comment by softsyst** [comment]
Hi Heiko,

Not sure whether I understand your motivation correctly. 
I have no idea yet what would be the effort to measure the pilot tone of 19kHz with an accuracy of 1mHz. The problem sounds interesting though. I'll think about it. In any case the requirement in the resolution would be orders of magnitude higher than what the audio spectrum currently delivers. However, the necessity would be to measure only the pilot and not the rest of the spectrum as well. 

Clem

**Comment by softsyst** [comment]
Heiko,

Some experiments were made. The method is straightforward: Take the isolated 19kHz carrier, downsample it to the lowest possible frequency (Nyquist), collect a sufficiently long buffer, dump it into a suitable FFT, and read the frequency. In that way, it seems well possible to get an accuracy of <10mHz. I'll come in a moment to the 1mHz issue.

The steps:

Before starting: the used device frequencies were DAB-calibrated.

1. A narrow IIR Filter of the 19kHz carrier, as is already present for the stereo processing. To determine an accurate bandwidth of that filter has not been done.
2. Downsample this (real-valued) signal to 64ksps, from 256ksps. A no-brainer. The least possible sampling rate would be 38kHz, and the next power of two is 64ksps, for easy processing.
3. No comes the step to get the FFT with a suitable resolution. I selected a buffer length of about 4Msamples, leading to an accuracy of 64ksps/4M -> 15mHz. 
4. Problem: The time for collecting the buffer. With the indicated numbers, it takes about 1 minute for a measurement. If we increase the accuracy by a factor of 10, we needed 10 minutes for a measurement, which is unrealistic.
5. The last step is the readout of the value. You see on the pictures that I - for this rapid prototype - omitted the horizontal scale, but the yellow triangle on top is an indication for 19000.00Hz, and the frequency of the peak is indicated by the tooltip of the cursor. If this method should make it into the product, of course the horizontal scale must be provided.

The pictures assume an exact sampling rate of 64kHz, thus the relative difference between stations might be deduced from the pictures. The value of the exact sampling rate accuracy is a separate problem, affecting the absolute frequency accuracy. I will try to get a value from sdrplay, as the RSPdx can be fed with an external reference frequency, which I could provide rather accurately (Rubidium Standard). I am not sure whether the sampling rate accuracy is the same as the DAB-calibrated frequency accuracy.

Here some pictures, estimated accuracy 15mHz, as expected:

Unzoomed hr2 overview:
![19kHz_hr2](https://github.com/user-attachments/assets/f1ce74a3-aaa9-449c-91a5-d737b2659667)

DLF
![19kHz_DLF_30mHz](https://github.com/user-attachments/assets/225e2c8d-a499-47dd-b9e0-cbf77685619a)

hr2
![19kHz_hr2_0mHz](https://github.com/user-attachments/assets/edece218-419a-4ce7-b162-b1c16356e32c)

BR-KLASSIK (weak, upper end of the spectrum, near 108MHz):
![19kHz_BRKLASS_RSP_m200mHz](https://github.com/user-attachments/assets/c7c78ad7-1d27-4444-aa97-2a1b18458887)

BR2 (weak, lower end of the spectrum, near 89MHz)
![19kHz_BR2_RSP_m200mHz](https://github.com/user-attachments/assets/ee3e0f04-152d-4882-9e0e-c264a65f8675)

FFH
![19kHz_FFH_RSP_50mHz](https://github.com/user-attachments/assets/6e67afe8-9833-427c-a04a-c71d4ac1b784)

So much for now.

Clem

**Comment by Drehrumbum** [comment]
Hello Clem!

Sorry for the delayed answer and many thanks for your first experiments! Looks good so far.

Well, I'm not a DSP guru, but related to the problem: We can shorten up the time for collecting time-domain data in front of an FFT by zero-padding the input-buffer till its end after we filled it up with data just for some seconds. Our pilot-tone is stable (it doesn't wobbling around within some seconds) and stands relative free, so we'll find its sharp peak-frequency in the spectrum, if we we zero-pad the buffer. It's the same like in this article: 

https://dsp.stackexchange.com/questions/11560/why-do-we-say-that-zero-padding-doesnt-really-increase-frequency-resolution?rq=1

Heiko

**Comment by softsyst** [comment]
No problem with the delay! 
Thanks for the link. I'll have a look and try. Seems too easy! Sadly, the link for the app in the referenced rundfunkforum thread seems to be dead.

Clem

**Comment by Drehrumbum** [comment]
The program is still there (https://www.qsl.net/dl4yhf/spectra1.html) and real cool stuff:

The last time I used this program was a good 15 years ago when I saw a strong line at about 32.7 kHz in the spectrum of 96 kHz voice recordings done with condenser-mics at home. It was (of course) the quartz in my watch that was "roaring" into the recordings purely acoustically. This was easily detectable with this program after I moved this frequency into the audible range in real-time and heard the Doppler effect when moving my arm... ;)

**Comment by Drehrumbum** [comment]
Just to say it. If you need a "tester" for all this stuff, my dongle is "really good" when it is warm.
 
![my_dongle](https://github.com/user-attachments/assets/da9836d3-8346-4c24-892e-913c2f4f0df0)

And then we could use the high power transmitters from Brocken, which should also reach Frankfurt. Here in the example the 100 kW ND from "radio SAW" with the much too short DAB antenna. AFAIK, "radio SAW" from Brocken reaches Hamburg ("Elbtunnel")...

![radio_saw](https://github.com/user-attachments/assets/2dcb5758-a7ce-4e99-ade1-365ecad2d7d1)


BFN Heiko

**Comment by softsyst** [comment]
Thanks for the updated link. Next step will be to make a test with the padding method. Currently I have not too much time, due to personal obligations. If I have something, of course you can get a version for testing.
On 101.4 I get a station. It's Radio Bob, 200W from "Ginnheimer Spargel" aka Ffm Europaturm.

Clem

**Comment by softsyst** [comment]
Heiko,

Sorry for the delay. Foolish as I was, I wrote the comment and (obviously) forgot to push the button. This was already last week. 
Anyway, here come the tests with the padding. The method seems to work.

The first pic shows the fft of a 4M buffer, filled from the start with 524288 samples, 8 seconds duration, the rest padded with zeros. The yellow triangle again shows the 19000Hz position. The peak is at about 250mHz lower than the 19k position:
![image](https://github.com/user-attachments/assets/0eeb4a0f-abce-4009-af5f-2d48cce3440a)

The 2nd pic shows the 4M buffer fft of the same signal, filled from start with 262144 samples, 4 seconds duration, rest zeros.
![image](https://github.com/user-attachments/assets/6bd4b586-d996-41e4-a67a-757950b09e99)

The padding is an interpolation. The math foundation is described [here](https://dsp.stackexchange.com/questions/24410/zero-padding-of-fft/24426#24426).

Possibly, this can be further optimized.

Clem

**Comment by Drehrumbum** [comment]
Hi Clem!

Well done. ;)  It seems, the interpolation (and the side-lobes next to the peak) because of zero-padding the buffer doesn't bother us. It’s just the price we have to pay for a real short sampling-time. (Okay, we only can do that in this special case because there is only some noise next to the much stronger and stable pilot tone.) But the most important thing is that the peak of the pilot tone is exactly where it is when you fill the buffer completely with samples.

This brings me to the next step, which I think you've already tried:

We can
- use longer FFTs
- (freely) adjust the number of samples in the buffer

TIA & BFN
Heiko

**Comment by softsyst** [comment]
Heiko,

after some time, I have a running solution based on your suggestion and my tests, with the 8sec filling buffer. Doesn't look spectacular, but should work:

![image](https://github.com/user-attachments/assets/ca0dddf6-5403-42b2-bb84-2e6aa0f940db)

Pushing the "Calc. Stereo Pilot Freq." button starts the calculation in the background,independent from what is displayed on the GUI. The result is displayed every 8 seconds, with an indication of 1mHz, obtained from a padded 4M real-valued FFT spectrum of the narrowly filtered 19kHz carrier, as described in the last posting.
 However:

- I would not bet on the accuracy of that 1mHz. I estimate the accuracy +-5mHz, although the indication (in the log) often is stable on all four decimal sub-Hz places, which can be read in a "Debug" log.
- The calculation gets the frequency from the coordinate of the maximum value in the spectrum, and interpolates with its two nearest neighbors.
- The absence of a Stereo Pilot is not taken into account (currently). But in that case usually the indication always changes some Hz, which it never does with a Stereo Pilot present.
- The absolute value depends on the calibration of the rx. It seems to be in the same range as the ppm error. Tests with a RSPdx and  a RTL-SDR V4 dongle showed the identical values on both (calibrated with DAB 5C) devices.

Due to the effort, I did not put work into more flexibility with respect to the parameters. If this proves to be useful, we could think about it.


I intend to include this into the next version, soon to come.

Clem

**Comment by softsyst** [comment]
Realized in V4.2.4
