### ISSUE TITLE
v.4.2.4 No TII Codes

### ISSUE THREAD

**Issue by MikeFallon** [softsyst/qirx_issues#165]
Hi Clem,
I have installed v.4.2.4 but I have no TII codes displayed. 
Thanks
Mike

**Comment by WIHDIA** [comment]
Hi Mike,

I had the same problem and it was easily fixed. Just run the msi again and choose Uninstall QIRX. Then run it again to install QIRX and the problem is solved. Settings are kept. 

73

Herman
[My logblog](https://wijnants.info/fmdx/)
Belgium editor of [fmlist.org](https://www.fmlist.org/)

**Comment by MikeFallon** [comment]
Excellent, that fixed it! Many thanks Herman

Mike

**Comment by softsyst** [comment]
I put a new version silently online, which should fix the issue. If you are in doubt about your version, compare the SHA-1 hash value of the downloaded .msi file.
