### ISSUE TITLE
Audio Spectrum in DAB-mode

### ISSUE THREAD

**Issue by esplien** [softsyst/qirx_issues#18]
In some cases it would be interesting to see the audio spectrum of a DAB-program. For example when two programs are sending the same stream, but may have different audio-processing, which I experienced last sunday.  Each program may have its own settings and the sound may vary with the program/channel chiefs choice or evt errouneously by settings by time.

**Comment by softsyst** [comment]
This is already realized. Right click into a free space of the DAB spectra part, select "Create Audio Spectrum".

**Comment by esplien** [comment]
Thank you Clem, I must have missed that...
