### ISSUE TITLE
Site names in TII-list

### ISSUE THREAD

**Issue by esplien** [softsyst/qirx_issues#19]
I would like to be able to see Site names from the database. In these digital days one should not be relying on a list to see the site name. Due to limited space in the TII-window, it could be by toggling TII-code/site with a button.

**Comment by softsyst** [comment]
You see the name when hovering over the map symbol. Shouldn't it be sufficient?

Additionally, you can inspect the whole content of the database for a TII by right-clicking into the symbol on the map and select "Info".
The TII window is not connected to the database and will not receive DB content.

**Comment by esplien** [comment]
Hi, ok, I can see SITE-name when hovering the map, when map is open. I unfortunately used a wrong name (TII-window) on the window, but I mean the TII-tab where TII main and sub could be repaced when checked by a suitable number of characters from SITE-name. ![bilde](https://user-images.githubusercontent.com/86978465/131992242-67e2c63b-0756-409b-8a08-114cb4662727.png)

**Comment by softsyst** [comment]
Espen,

I understood very well what you meant. This tab will not receive the site name, as it is available on the map, and the tab has no connection to the database. 
Thus, to see the site name, you need the map. 

73,
Clem

**Comment by WIHDIA** [comment]
I do see Esplien's point. Is it _technically_ impossible to connect the map data to the tab?

**Comment by softsyst** [comment]
No, of course _technically_ not.

**Comment by DABodr** [comment]
Is it possible to add the transmitter site name to the log file? It could make it easier to identify the transmitter's location.

**Comment by softsyst** [comment]
As there seems to be an enhanced interest in this issue, I will again check the effort.
Thanks for input!

**Comment by WIHDIA** [comment]
Hi,

That would indeed be nice upgrade/new feature!

⁣73

Herman Wijnants
My logblog​


-------- Oorspronkelijk bericht --------
Van: RSAP ***@***.***>
Verzonden: Sun Nov 05 14:04:28 GMT+01:00 2023
Aan: softsyst/qirx_issues ***@***.***>
Cc: Herman ***@***.***>, Comment ***@***.***>
Onderwerp: Re: [softsyst/qirx_issues] Site names in TII-list (#19)

Is it possible to add the transmitter site name to the log file? It could make it easier to identify the transmitter's location.

**Comment by softsyst** [comment]
As the feature has been realized in 4.1.3, I close this one.
