### ISSUE TITLE
Taskbar hidden

### ISSUE THREAD

**Issue by WIHDIA** [softsyst/qirx_issues#2]
When maximizing QIRX the Windows 10 tasbkar is hidden.

**Comment by softsyst** [comment]
Happens with fixed taskbars. A thorough investigation showed that no easy solution seems possible. Suggested workaround: Change the taskbar to "autohide". Then it should work.

**Comment by WIHDIA** [comment]
OK.

**Comment by softsyst** [comment]
No more actions planned. I close it.
