### ISSUE TITLE
Create Desktop Item

### ISSUE THREAD

**Issue by WIHDIA** [softsyst/qirx_issues#21]
The installer asks the user to tick a box asking the user whether or not to create a desktop item. The installer always creates it even I you did not choose to.

**Comment by softsyst** [comment]
I was terribly mislead when I thought a fix would not take more than five minutes. Sadly, after investigating it half a day I found no easy solution. 
As a workaround and assuming that most people would like to have such an icon, I will omit the page with the checkbox selection. 
For you this means that you have to delete it after every installation.
Sorry for this!
For the time being, I leave this issue open, in the hope to find a solution.

**Comment by softsyst** [comment]
I close this issue as I could not find an easy solution in Windows installer. The bug has been"resolved" by removing the check box. Please re-open if you find it necessary.
