### ISSUE TITLE
Problem on Win10Pro desktop

### ISSUE THREAD

**Issue by esplien** [softsyst/qirx_issues#23]
Qirx has been working on this hp z420 computer win Win10Pro 64b for a loong time. But now any qirx cannot connect to 127.0.0.1:1234 after 1 or 3 attempts depending on version. Also the settings window is totally blank. It seems to be problem with PCI serial controller and SAS controller. Any idea on how to fix? 
![bilde](https://user-images.githubusercontent.com/86978465/137707545-510474be-0914-4fed-bf0b-1a6c33fc93cb.png)

Enhetsnavn	DESKTOP-6TV77M9
Prosessor	Intel(R) Xeon(R) CPU E5-1650 0 @ 3.20GHz   3.20 GHz
Installert RAM	8,00 GB
Enhets-ID	B4503F9D-532D-4C28-A1A7-58EA263A41F0
Produkt-ID	00330-80000-00000-AA206
Systemtype	64-biters operativsystem, x64-basert prosessor
Penn og berøring	Ingen penne- og berøringsinndata er tilgjengelige for denne skjermen

Versjon	Windows 10 Pro
Versjon	21H1
Installert den	‎16.‎08.‎2021
Operativsystembygg	19043.1288
Opplevelse	Windows Feature Experience Pack 120.2212.3920.0

//Espen

**Comment by softsyst** [comment]
Unfortunately, no idea. Did you change anything on your system ?

**Comment by esplien** [comment]
Hi,

There has been a couple Of windows updates, and I have tried AGV internet security, and removed it, but problem was still there…



//Espen 
Sendt fra min iPhone

**Comment by softsyst** [comment]
W/r to the missing Settings GUI, I have no clue.
 
What you could try for the connect (see also the Install instructions on the website):

- Manually edit the config file. You are navigated directly to the directory by clicking on the Home button in QIRX.
- There, for the receiver number you are using, set "autostart" and "autostop" to "false".
- Start the rtl_tcp manually on the command line.

- Does the rtl_tcp recognize the hardware? If not, you should reinstall the driver by using Zadig. These drivers have repeatedly been reported to be reset by Windows updates.
- In case the hardware is recognized, can you connect from QIRX?

**Comment by esplien** [comment]
Thanks for your tips!
I'll try your suggestions as soon as I get hands on the computer

73 de


 
Espen 
LA1RQ
 

    På fredag 22. oktober 2021, 10:53:10 CEST skrev softsyst ***@***.***> følgende:  
 
 


W/r to the missing Settings GUI, I have no clue.

What you could try for the connect (see also the Install instructions on the website):
   
   -    
Manually edit the config file. You are navigated directly to the directory by clicking on the Home button in QIRX.

   -    
There, for the receiver number you are using, set "autostart" and "autostop" to "false".

   -    
Start the rtl_tcp manually on the command line.

   -    
Does the rtl_tcp recognize the hardware? If not, you should reinstall the driver by using Zadig. These drivers have repeatedly been reported to be reset by Windows updates.

   -    
In case the hardware is recognized, can you connect from QIRX?


—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by softsyst** [comment]
@esplien 
Do you have any new info about this? Please feedback, whether I can close it or not.

**Comment by esplien** [comment]
Hi Clem,
Thanks for the reminder! 

I found another issue on the Computer, namely a very noisy (acoustic) cooling fan on the graphics card, a Radeon Quadra 2000, which is a well known issue. Tried some easy fix, but will probably end up buying a new graphic card.

In the mean time,I have been completing an other project; remote control of my Elad transceiver/PA fmand a new antenna: Diamond WD330j. At this moment You may close this issue, I will eventually pick it up again if problem is still there.

73 de Espen 
Sendt fra min iPhone

**Comment by softsyst** [comment]
Hi Espen,

thanks for your feedback. I close this now. Feel free to re-open if you think it's necessary.

Clem

PS Fans are evil.
