### ISSUE TITLE
Deleting *.tmp files

### ISSUE THREAD

**Issue by WIHDIA** [softsyst/qirx_issues#24]
I would be nice if in the database folder (C:\Users\***\AppData\Local\qirx3\Database ) the tmp files would be deleted after closing down QIRX.

73

Herman
[My logblog](https://wijnants.info/fmdx/)

**Comment by softsyst** [comment]
Thanks for this reminder!

**Comment by softsyst** [comment]
Herman, could you check if this is working now correctly? If so, I could close the issue.

**Comment by WIHDIA** [comment]
PERFECT!
