### ISSUE TITLE
Wiping in DAB spectrum

### ISSUE THREAD

**Issue by andimik** [softsyst/qirx_issues#25]
when you wipe left or right in the DAB spectrum, the frequency changes and no signal can be decoded.

![grafik](https://user-images.githubusercontent.com/24510556/142719800-55f7839d-2abb-40f7-99ff-e8c347a57621.png)

Either disable it or move to the next DAB channel (which would be an alternative for the ensemble selector drop down)

**Comment by softsyst** [comment]
What do you mean by "wipe"? Please elaborate how to reproduce the behavior.

**Comment by andimik** [comment]
Nachdem wir beide deutsch sprechen, ich verschiebe mit der linken Maustaste einfach die Frequenz nach links oder rechts. Das bringt bei DAB ja nichts. Stattdessen könnte man auf den vorigen bzw. folgenden Kanal springen.

**Comment by softsyst** [comment]
Ganz so ist es nicht. Es kann durchaus Sinn machen, auch bei DAB die Frequenz zu verschieben. Z.B. wenn man keinen Rx hat, der einen Frequenzfehler hat. Dann kann man die Frequenz um einen bestimmten Betrag verschieben (Device Frequenz oder Mausklick) und sehen, ob das Programm diese Verschiebung noch korrigieren kann.
Da könnte man weitere Beispiele anfügen.
Es wäre mMn auch eine Vermischung von "Frontend" Eigenschaften mit DAB Eigenschaften, die ich ungern hätte. Der Frontend Teil "weiß" erstmal nichts von DAB (oder anderen Demodulatoren).

Es gibt aber in diesem Zusammenhang einen sehr unangenehmen Fehler, wo ich allerdings keine Lösung habe:
Man kann in Windows ein Programm durch Doppelklick auf die obere Leiste maximieren. Wenn man das in einem Bereich über dem Spektrum macht, verstellt sich die Frequenz. Wahrscheinlich wird der zweite Klick vom Doppelklick auch als Klick in das Spektrum gewertet und verstellt die Frequenz.

Und wegen Englisch war das weniger um Englisch zu schreiben, sondern weil möglicherweise auch Leute mitlesen, die kein Deutsch sprechen.
