### ISSUE TITLE
'Stop receiver' button disappears after rtl-tcp connection fail

### ISSUE THREAD

**Issue by andimik** [softsyst/qirx_issues#26]
When autostart is set to off 

![grafik](https://user-images.githubusercontent.com/24510556/142719919-3b64f2b3-4524-4923-abb3-f81761ab52c2.png)

press the blue arrow
![grafik](https://user-images.githubusercontent.com/24510556/142719996-4efdeff0-ad63-41b6-bf11-7622a826d668.png)

then the message `Please start rtl-tcp.exe or another IQ data source manually` appears.

In case you click on OK **without** having started rtl-tcp then the warning `Connect to 127.0.0.1:1234 failed after 1 attempts` appears (which is ok of course).

**But now the red cross disappears for the current session.**

Even if you start rtl-tcp now and repeat the steps you cannot stop the receiver anymore without stopping Qirx itself.

![grafik](https://user-images.githubusercontent.com/24510556/142720110-a1a4fd8b-ef31-4c7d-a4dd-8c8595ccdf69.png)

Or change the message text into `Please start rtl-tcp.exe or another IQ data source manually now and then click ok to continue`

**Comment by andimik** [comment]
Additionally, when you then press the green arrow and select a raw file the rtl_tcp will continue but the windows shows the raw file loading progress.

![grafik](https://user-images.githubusercontent.com/24510556/142720490-81a4dd98-1a7e-415a-ba1b-9cee4d6bcddc.png)

**Comment by softsyst** [comment]
An old bug which was not cleared completely.

**Comment by softsyst** [comment]
@andimik could you check if the 3.2.1 still shows the issue?

**Comment by andimik** [comment]
Yes, confirmed. Solved in 3.2.1. Thanks!
