### ISSUE TITLE
Show map only works right after start

### ISSUE THREAD

**Issue by andimik** [softsyst/qirx_issues#29]
In 3.2.1 the Show Map button does only work right after the start as long as the connection has not been started yet.

As soon as a DAB Signal is played, a click on the icon has no effect.

Qirx has to be restarted (and click on the icon then) in order to show the map.

**Comment by softsyst** [comment]
Similar to the TII error, I cannot reproduce this.

**Comment by andimik** [comment]
Fixed after I have uninstalled Qirx and re-installed again. This behaviour is the same as described in #28
