### ISSUE TITLE
EPG icon

### ISSUE THREAD

**Issue by WIHDIA** [softsyst/qirx_issues#3]
Perhaps change the non-EPG mux stations list icons from an musical note in a simple dot of the same colour as the notes?

**Comment by softsyst** [comment]
The icon was added 
- to distinguish services without EPG logos from ones with such logos,
- as a preparation for future releases implementing not only audio, but also data services. These will get a different icon. The suggested dot would not serve in that case.

**Comment by WIHDIA** [comment]
Hi Clem,
I don't understand. I installed 3.1.4 with a new config, changed some paths and the musical notes are still there.
73
Herman

**Comment by softsyst** [comment]
My comment was to explain why the musical note will remain.
73,
Clem

**Comment by WIHDIA** [comment]
Ok. A bit of a misunderstanding then. What's new in 3.1.4 then? Preparations for the next step and under the hood?

⁣73

Herman Wijnants
www.wijnants.info​


-------- Oorspronkelijk bericht --------
Van: softsyst ***@***.***>
Verzonden: Sat Jul 03 13:59:08 GMT+02:00 2021
Aan: softsyst/qirx_issues ***@***.***>
Cc: Herman ***@***.***>, Author ***@***.***>
Onderwerp: Re: [softsyst/qirx_issues] EPG icon (#3)

My comment was to explain why the musical note will remain.
73,
Clem

**Comment by softsyst** [comment]
OK, Herman. I close the issue. See also my PM.
