### ISSUE TITLE
SPI services are 0 kBit/s and SId is 0 in 0.9.3

### ISSUE THREAD

**Issue by andimik** [softsyst/qirx_issues#30]
In previous 0.9.1, a user could even select the SPI data service (which is invisible in Qirx) in order to get all SPI related files and save them to the directory `~/.local/share/qirxConsole/SPI`

![Bildschirmfoto vom 2022-01-16 19-25-19](https://user-images.githubusercontent.com/24510556/149673217-6cd942e0-3739-45da-8447-b6659c283043.png)

```
./qirxConsole 

cQIRX for DAB, V0.9.1

[...]

>ens=6A
Creating Ensemble 6A 
DAB Synced after 1 seconds
Block: 6A, Name: DAB+ Austria, EId: A101
Available Services:
[...]
EPG ORS
[...]

>serv=EPG ORS
Service EPG ORS available after 0 seconds
Service: EPG ORS, SId: E0A0AD50, Bitrate: 16kbps
```

But in 0.9.3 this does not work any more, the service is detected as 0 kBit/s and the SId is 0 (see below). Therefore, no files are stored in the above mentioned directory any more.

```
./qirxConsole 
cQIRX, V0.9.3

[...]

>ens=6A
Creating Ensemble 6A 
DAB Synced after 1 seconds
Block: 6A, Name: DAB+ Austria, EId: A101
Available Services:
[...]
EPG ORS
[...]

>serv=EPG ORS
Service EPG ORS available after 0 seconds
Service: EPG ORS, SId: 0, Bitrate: 0kbps
```

Same in the Windows version, so not related to Linux only.

Hint: Audio services do work:

```
serv=WELLE 1
Service WELLE 1 available after 0 seconds
Service: WELLE 1, SId: AD58, Bitrate: 72kbps
```

**Comment by softsyst** [comment]
Sorry, never tested this. SPI is currently not intended to be used in the console version, however, the running log does not show anomalies. I'll check! Thanks for the report!

A value of zero for SId is not correct. This works here.

**Comment by andimik** [comment]
I could test with raw files generated from German's Bundesmux 5C or Bayern 11D which I can receive on satellite (I found out how to use raw files thanks to Matthias Brändli even for tools like cqirx NOT having a file interface)

**Comment by andimik** [comment]
I also tried Slovenian's national mux. 0.9.1 exports the files, 0.9.3 does not and the SPI is 0 kBit as well and its SId became 0 in 0.9.3, too.

**Comment by andimik** [comment]
In the past hours (time goes by really fast ...) I've investigated the issue with the following ensembles

| Country | Mux | 0.9.1 | 0.9.3 |
|---------|-----|-------|-------|
|Italy    |12C  | yes   | no    |
|Italy    |12A  | yes   | no    |
|Germany  |5C   | yes   | partly|
|Norway   |NRK1 | yes   | partly|
|Austria  |ORS  | yes   | no    |
|Slovenia |R1   | yes   | no    |


On Bundesmux my tests gave quite a random result, sometimes the SPI shows 16kBit or 0 kBit, but the SId always was 0, indeed, the rest of the data services show either 0 kBit and SId 0 or even the correct values.

So I get

# 0.9.1

```
>serv=DRadio Daten
Service DRadio Daten available after 0 seconds
Service: DRadio Daten, SId: E0D00250, Bitrate: 32kbps

>serv=TPEG
Service TPEG available after 0 seconds
Service: TPEG, SId: E0D010BC, Bitrate: 16kbps

>serv=TPEG_MM
Service TPEG_MM available after 0 seconds
Service: TPEG_MM, SId: E0D310BC, Bitrate: 16kbps

>serv=EPG Deutschland
Service EPG Deutschland available after 0 seconds
Service: EPG Deutschland, SId: E0D110BC, Bitrate: 16kbps
```

but 

# 0.9.3

```
>serv=EPG Deutschland
Service EPG Deutschland available after 0 seconds
Service: EPG Deutschland, SId: 0, Bitrate: 0kbps

>serv=TPEG
Service TPEG available after 0 seconds
Service: TPEG, SId: E0D010BC, Bitrate: 16kbps

>serv=TPEG_MM
Service TPEG_MM available after 0 seconds
Service: TPEG_MM, SId: E0D310BC, Bitrate: 16kbps

>serv=DRadio Daten
Service DRadio Daten available after 0 seconds
Service: DRadio Daten, SId: E0D00250, Bitrate: 32kbps
```



# Italy

## 12C

```
cQIRX, V0.9.3
[...]
Block: foo, Name: * DAB Italia *, EId: 5009
Available Services:
[...]
EPG
[...]

>serv=EPG
Service EPG available after 0 seconds
Service: EPG, SId: 0, Bitrate: 0kbps
```

## 12A


```
cQIRX, V0.9.3
[...]
Block: foo, Name: #EuroDab Italia, EId: 5003
Available Services:
[...]
EPG-SI
[...]

>serv=EPG-SI
Service EPG-SI available after 0 seconds
Service: EPG-SI, SId: 0, Bitrate: 0kbps
```

# Norway NRK1

## 0.9.3

```
>serv=NRK EPG Reg 1
Service NRK EPG Reg 1 available after 0 seconds
Service: NRK EPG Reg 1, SId: 0, Bitrate: 0kbps

>serv=NRK TPEG Reg1
Service NRK TPEG Reg1 available after 0 seconds
Service: NRK TPEG Reg1, SId: E2F20001, Bitrate: 32kbps
```
And so on. 

I also have very short dropouts in Audio in 0.9.3 (even with local terrestrial DAB), and sometimes 0.9.3 does not show all services from the mux, so I fear there is a sync problem in general.

**Comment by softsyst** [comment]
Hi Andi,

I found the bug and put just a new Windows console  version online. Linux will follow tomorrow (hopefully), together with the #32.
Your "partly" results astonish, I would have expected "nothing". 
In that version all info residing in the "Kernel", represented by the file Resources.dll, is handled by "interfaces" to their respective DLLs, and not by the accessing the DLLs of the Kernel directly. One of these interfaces dealing with MOT behavior did not load properly in the console version. In the GUI version it was ok.

In 0.9.1 this was not handled as stringent as it is now. 
Let's see if it works now.

Again, thanks for your effort!

An incomplete mux service list should be shown completely by refreshing it with "ens". 

On Windows, dropouts are absent here. I have some in Linux, shown by ALSA output strings. I attributed this to my handling of Portaudio. The usual way is to provide a callback to portaudio, but I do it the other (also legal) way without callbacks, as the callback interfacing from C# to C is rather clumsy code. I do not know the performance of the .net in Linux.

Clem

**Comment by andimik** [comment]
Ok, will try in the evening.

> ALSA

Oh, you are right, I have checked qirxAudio's console output now and confirm lots of lines coming from ALSA.

**Comment by andimik** [comment]
Confirmed, the updated 0.9.3 now works. Have tried with Austrian national mux under Windows 10.

```
cQIRX, V0.9.3

[...]
EPG ORS
[...]

>serv=EPG ORS
Service EPG ORS available after 0 seconds
Service: EPG ORS, SId: E0A0AD50, Bitrate: 16kbps
```

![Screenshot (305)](https://user-images.githubusercontent.com/24510556/150003958-c6e92af4-16e2-497b-a204-49336189487f.png)

But I still wonder why cQirx is renaming all the files, because the real files names are as followed:

```
A3DD_R.Maria_112x32.png
A3DD_R.Maria_128x128.png
A3DD_R.Maria_320x240.png
A3DD_R.Maria_32x32.png
A3E0_Austria_112x32.png
A3E0_Austria_128x128.png
A3E0_Austria_320x240.png
A3E0_Austria_32x32.png
AC47_88.6_112x32.png
AC47_88.6_128x128.png
AC47_88.6_320x240.png
AC47_88.6_32x32.png
AC51_ENERGY_112x32.png
AC51_ENERGY_128x128.png
AC51_ENERGY_320x240.png
AC51_ENERGY_32x32.png
```
and so on ...

Therefore, I'm closing this issue.
