### ISSUE TITLE
QIRX Crash with .NET6

### ISSUE THREAD

**Issue by softsyst** [softsyst/qirx_issues#31]
There seems to be a bug in .net6 which can crash the app in the following scenario:
1. In DAB, move the mouse into one of the spectrum windows, e.g. TII. A tooltip appears showing some info.
2. Now move it to the left side out of the spectrum, but stay inside the TII window. The tooltip disappears.
3. Now move it into the spectrum again.
Every now and then this crashes the program. The crashes show up almost reproducibly, when you 
4. Open the context menu with a right mouse click in the spectrum window.

This or a similar behavior has been reported by a number of users [here on this site](https://github.com/dotnet/wpf/issues/5730) who also migrated from net5 to net6. I have no information yet about a fix or a possible workaround.
Please try to avoid the described scenario. The crash seems to take place in the WPF part.

Clem

**Comment by WIHDIA** [comment]
Hmm tried it half a dozen times, but no crash. However yesterday evening I left QIRX running in the background and then it crashed. This happened only once.

**Comment by andimik** [comment]
It's not only related to 3.2.1, I get the above described crash in 3.2.2, too. So you could rename the issue.

But I cannot advise as I'm not a programmer …

**Comment by softsyst** [comment]
Thanks for the hint. You are very right, of course.

**Comment by softsyst** [comment]
Please anyone comment if the problem still persists. To me, it seems that MS solved it. But I'll leave it still open for some days.

**Comment by softsyst** [comment]
No negative feedback any more. I assume MS fixed it. I close this issue. Please feel free to re-open if necessary.
