### ISSUE TITLE
cQirx's behavior after rtl_tcp loss

### ISSUE THREAD

**Issue by andimik** [softsyst/qirx_issues#32]
This happens in both, 0.9.1 and 0.9.3 under Linux.

```
>serv=WELLE 1
Service WELLE 1 available after 0 seconds
Service: WELLE 1, SId: AD58, Bitrate: 72kbps

>serv=ERF Plus
Service ERF Plus available after 0 seconds
Service: ERF Plus, SId: AD24, Bitrate: 40kbps
```
then I cut `rtl_tcp`:
```
>serv=WELLE 1
Service WELLE 1 available after 0 seconds
Service: WELLE 1, SId: AD24, Bitrate: 0kbps
```

Expected behavior is to print `Cannot synchronize ensemble` or show SId 0.
But cQirx prints the SId of the last tuned service.

**Comment by andimik** [comment]
No, the updated 0.9.3 from yesterday 18th Jan did not solve it.

```
$ ls -l | grep Console
-rwxrwxrwx 1 andreas andreas 65012161 Jän 18 16:05 qirxConsole
-rw-rw-r-- 1 andreas andreas     8954 Jän 15 11:56 qirxConsole.config
```

```
>serv=WELLE 1
Service WELLE 1 available after 0 seconds
Service: WELLE 1, SId: AD58, Bitrate: 72kbps

>serv=ERF Plus
Service ERF Plus available after 0 seconds
Service: ERF Plus, SId: AD24, Bitrate: 40kbps
```
then I close rtl_tcp:

```
>serv=WELLE 1
Service WELLE 1 available after 0 seconds
Service: WELLE 1, SId: AD24, Bitrate: 0kbps
```

**Comment by softsyst** [comment]
Hi Andi,

I considered this an important one and spent some effort in the 4.0.9, as well as in the 0.9.4 Linux.
Now in both versions the SW is running a heartbeat of some seconds, and if you "pull the TCP/IP plug", no data are arriving any more, a "data arriving" flag will not be set, which is interpreted after the timeout. In the case of "no data arrived", in the Console Version, a text message should appear to inform the user and stop the whole thing, and in the GUI version on Windows the same happens after a message box.
Please check if this works, that I could close the issue. Take your time!

Thanks again for this - important - input!
Best,
Clem

**Comment by andimik** [comment]
Oh, thank you very much for the investigations. I will try the new versions in the next days.

**Comment by softsyst** [comment]
No more inputs. I close it.
