### ISSUE TITLE
Suggestion: LNA State RPS1A

### ISSUE THREAD

**Issue by WIHDIA** [softsyst/qirx_issues#34]
Wouldn't it be a bit more user friendly if QIRX 3.2.1+RSP1A would remember the LAN state from the previous session?
It now resets to default 3 after a restart of the Rx. 2 vs 3 also seems to have no effect on very strong locals at my location, but that might be different for other users. Even better: remembering LNA state settings for each mux.

73
Herman

**Comment by softsyst** [comment]
Yes, I agree. Thanks for putting it here. Not mux-individually though.

**Comment by softsyst** [comment]
Hi Herman,
should be ok in the 3.2.2. Could you confirm?

73,
Clem

**Comment by WIHDIA** [comment]
CONFIRMED. 3.2.2 keeps the LNA state after closing down. Excellent.

**Comment by softsyst** [comment]
Thanks for comment. I close this one.
