### ISSUE TITLE
RSP3_tcp.exe detected as Malware by AVIRA 

### ISSUE THREAD

**Issue by oliverathome** [softsyst/qirx_issues#35]
When installing QIRX 3.2.1 Windows10 RSP3_tcp.exe is detected as HEUR Malware by AVIRA Free Security Suite, and moved in quarantine.

![grafik](https://user-images.githubusercontent.com/62095477/151141021-cedb122d-385c-47b6-8578-c7df14062586.png)

Is this File safe to use ?

**Comment by softsyst** [comment]
Yes, it is. If you are in doubt, why not have a look in the sources? [It is on GitHub.](https://github.com/softsyst/RSP3_tcp)
Even better, you might build it yourself from there.

I just run a quick test on [virustotal.com](virustotal.com), and I can confirm your finding. 4 of 66 antivirus products flag it (Avira being one of them), 62 (including ESET what I am using here) don't. For whatever reason.

**Comment by softsyst** [comment]
No further comment arrived. I close this one.
