### ISSUE TITLE
DAB Tii Main/sub discrepancy between map and main window ?

### ISSUE THREAD

**Issue by F6FLT-Franc** [softsyst/qirx_issues#37]
1) In DAB I notice a discrepancy between the Main/Sub Tii noted on the card, and the Tii indicated in the main window. I made 2 screenshots that I put on my catch-all site:
http://exvacuo.free.fr/div/temp/DABNantes1.png
http://exvacuo.free.fr/div/temp/DABNantes2.png

 The first one is for an SFN with 2 transmitters. The second one is in single transmitter. In both cases the Tii do not match.

2) I also see that for the SFN network, I have only one transmitter on the map out of the two.

 Are these anomalies or am I missing something?

**Comment by softsyst** [comment]
Hi,
Without further info it is not possible to make a judgement. The most probable seems to be an error in the database.

What could be done to resolve the issue:
1. You could try to decode manually the Main/Sub Ids from the carrier positions in the TII spectrum. This should not be difficult, as the signals are strong.
2. I and/or others could try to do it, but for this raw data files of at least one or two minutes were necessary (two minutes raw => approx. 550MB file size). You could make a recording and post a link from where the files can be downloaded.

**Comment by softsyst** [comment]
@F6FLT-Franc 
I forwarded your question to the TII thread in the German [rundfunkforum](https://www.rundfunkforum.de/viewtopic.php?f=11&t=56477&p=1647319#p1647319).

Two postings, one of **@Jagsttal-DX** and another one of **@ulionken**, both experienced DXers with a knowledge of the DABLIST database, were received on this topic.

Please have a look at their answers. They are in German, but Google translator is your friend in case you should not be able to read it.

73,
Clem

**Comment by softsyst** [comment]
After the discussion in the rundfunkforum I close this issue.
