### ISSUE TITLE
EnsembleID on 10D DAB+ W-VL

### ISSUE THREAD

**Issue by WIHDIA** [softsyst/qirx_issues#38]
Hi Clem,

This morning I was able to hear 10D DAB+ W-VL from Roeselare. Nearby DAB+ Limburg can be completely muted with the stacked aerials.

Something odd with this mux. The ensemble ID is 0064 as you can see in [this screenshot](https://wijnants.info/fmdx/wp-content/uploads/2022/04/afbeelding-2.png) with QT-DAB.
However, no TII was shown in QIRX and it shows the ensemble ID as EE-64 as you can see [here](https://wijnants.info/fmdx/wp-content/uploads/2022/04/afbeelding-3.png). I updated the database but nothing happened on the map or the TII widget (no distance etc), while QT did show the location after updating!  I fixed it by manually changing the EID in the database to just 64.

73

Herman

**Comment by andimik** [comment]
Please note that there are 3 ensembles in Belgium with non-Belgian EId (= they are starting with 0xB or 0x0 like in this case).

**Comment by softsyst** [comment]
Hi Herman,

Yes, something seems to be odd with this mux. The correct behaviour by the software would be to reject it altogether, as the EId of 64 is forbidden by the standard. **@andimik** remarked correctly that this EId is not valid for Belgium. But furthermore, it is not valid at all.

The standard says in 6.4.1 "Ensemble Information", that the EId is a number of 16 bit. The lower 12bit is the "Ensemble reference" and the higher four bit is the "Country Id" which is 6 for Belgium. These numbers are indicated on the qirx GUI as hexadecimal, showing one character for every four bit, meaning that the EId with its 16 bits should be shown as four characters, as usual.

The EId of E0-64 or E0-0064 (which is the same) would be a country with Extended Country Code (ECC) of E0, which would be correct for Belgium, but also for some other countries. It is not unambiguous. The highest four bits of the 16-bit hexadecimal number 64 is zero, thus **this EId shows a Country Code of zero, which is forbidden** (ETSI TS101 756: "Country identifier code "0" is not used"). The apps seem to treat such bogus numbers too relaxed, as the right way would be to reject it.

@andimik  noticed a country code of B (Hainaut Ouest, Hainaut MCL), which would be Hungary (if used together with an ECC of E0). 

Maybe you can contact the mux provider and request them to read the Standard.

73,

Clem

**Comment by WIHDIA** [comment]
> Please note that there are 3 ensembles in Belgium with non-Belgian EId (= they are starting with 0xB or 0x0 like in this case).

Hi Andimik,

You are correct. There's e.g. 11B and 12B Hainaut.
73
Herman

**Comment by WIHDIA** [comment]
> Hi Herman,
> 
> Yes, something seems to be odd with this mux. The correct behaviour by the software would be to reject it altogether, as the EId of 64 is forbidden by the standard. **@andimik** remarked correctly that this EId is not valid for Belgium. But furthermore, it is not valid at all.
> 
> The standard says in 6.4.1 "Ensemble Information", that the EId is a number of 16 bit. The lower 12bit is the "Ensemble reference" and the higher four bit is the "Country Id" which is 6 for Belgium. These numbers are indicated on the qirx GUI as hexadecimal, showing one character for every four bit, meaning that the EId with its 16 bits should be shown as four characters, as usual.
> 
> The EId of E0-64 or E0-0064 (which is the same) would be a country with Extended Country Code (ECC) of E0, which would be correct for Belgium, but also for some other countries. It is not unambiguous. The highest four bits of the 16-bit hexadecimal number 64 is zero, thus **this EId shows a Country Code of zero, which is forbidden** (ETSI TS101 756: "Country identifier code "0" is not used"). The apps seem to treat such bogus numbers too relaxed, as the right way would be to reject it.
> 
> @andimik noticed a country code of B (Hainaut Ouest, Hainaut MCL), which would be Hungary (if used together with an ECC of E0).
> 
> Maybe you can contact the mux provider and request them to read the Standard.
> 
> 73,
> 
> Clem

I'll get in touch with the guys from W-VL and point out the error. Not sure if that will do :-)

73

Herman

**Comment by andimik** [comment]
Hint: the same problem occurs for example on https://www.digitalbitrate.com/dtv.php?mux=COULOMBY-12B-E0-B235&liste=1&live=186&lang=en as Philippe uses the ECC code for detecting the country.

In this case, the 0xB (in combination with the country code) is assigned to Hungary.

**Comment by softsyst** [comment]
No further comments received. I close this one.
