### ISSUE TITLE
NFM de-emphasis

### ISSUE THREAD

**Issue by esplien** [softsyst/qirx_issues#4]
As most amateur VHF/UHF FM transceivers uses a pre-emphasis with 750us characteristic, it is of interest to be able use the corresponding 750us de-emphasis in Qirx NFM to achieve a "flat" response of tx/rx and better S/N-ratio. Selectable of course.

**Comment by softsyst** [comment]
Espen,

I made a test implementation of the de-emphasis, in the NFM demodulator. I'll send you a PM.

73,
Clem

**Comment by esplien** [comment]
Hi Clem,

1. Message to advice me that I already had a the program, and adviced me to remove the program, which I did and managed to install Qirx4 NFM de-emph.

When trying to start RX1 after rekonfiguring to 1 rx:

RTl_tcp.exe reports (translated to English):
Code running cannot continue because VCRUNTIME140D was not found. New installation of the program might solve the problem.


Code running cannot continue beause Ucrtbased.dll was not found. New installation of the program might solve the problem.
 

73 de
Espen
LA1RQ

Sendt fra E-post for Windows 10

Fra: softsyst
Sendt: torsdag 8. juli 2021 kl. 15:20
Til: softsyst/qirx_issues
Kopi: esplien; Author
Emne: Re: [softsyst/qirx_issues] NFM de-emphasis (#4)

Espen,
I made a test implementation of the de-emphasis, in the NFM demodulator. I'll send you a PM.
73,
Clem

**Comment by softsyst** [comment]
Espen,

Problem #1 is normal behaviour, because this one has the same version as the already installed one. This will not change, because I'll not give such interim builds a new version.

Obviously, I had made a debug build necessitating the dll's you mentioned. Maybe you can download them from somewhere. I'll make a release build for you in any case, not sure if I manage today.

73,
Clem

**Comment by esplien** [comment]
Ok, Clem

I will go shopping and look after My daughters two cats…

Will Try to find the files.

//Espen 
Sendt fra min iPhone

**Comment by softsyst** [comment]
I'll probably not be able to rebuild the rtl_tcp tomorrow, due to other project obligations. You could take it from an older release and copy it into your current install directory, and test the de-emphasis. 

I'll get back to you if I found the time to do it.

73,
Clem

**Comment by esplien** [comment]
Oki, no rush! 

//Espen 
Sendt fra min iPhone

**Comment by esplien** [comment]
Hi Clem,

I have reinstalled th 3.14 version and copied  the vcruntime and ucrt… files, added into the installation folder of qirx v3 NFM de-emph the ucrt…dll  file was accepted; no error, but still error on vcrutime14D…dll missing…


73 de
Espen
LA1RQ

Sendt fra E-post for Windows 10

Fra: softsyst
Sendt: torsdag 8. juli 2021 kl. 22:21
Til: softsyst/qirx_issues
Kopi: esplien; Author
Emne: Re: [softsyst/qirx_issues] NFM de-emphasis (#4)

I'll probably not be able to rebuild the rtl_tcp tomorrow, due to other project obligations. You could take it from an older release and copy it into your current install directory, and test the de-emphasis.
I'll get back to you if I found the time to do it.
73,
Clem

**Comment by softsyst** [comment]
V 3.1.5 implements the NFM deemphasis.
