### ISSUE TITLE
Autodetection for 16bit sdr-files

### ISSUE THREAD

**Issue by andimik** [softsyst/qirx_issues#41]
When I want to load a 16bit `*.sdr`-File (which was created with **Qt-DAB**, I need to change the bit width for the dongle (!!!). 

I don't find that very user-friendly, because there is a (in this case useless) warning as well.

> Rx 1: RTL-SDR cannot receive 16 Bit, only 8 Bit.
> Do you want to continue anyway?

So, I suggest implementing an autodetection for 16bit sdr-files without the need to switch to 16bit in the settings.

![grafik](https://user-images.githubusercontent.com/24510556/181188963-e71a14fd-27e2-496e-84e7-3128db580410.png)

**Comment by softsyst** [comment]
You are right, this feature has been like this for some years. 

To avoid this, Jan and myself introduced the xml header files ("xml" file in qt-dab). Such files should set the sampling rate and the bitness automatically. This is the proper solution for the problem. The suggested auto-detect is not straightforward.
QIRX recordings always add the header to the recorded file.

The (misleading in that case) error message cannot easily be removed, as during "Setup" the SW does not know whether a life transmission or a file will be played. But a hint for the "file" case should be there.

As nobody has complained for some years now, the priority will not be too high. I'll check the effort.

A similar problem arises when you replay a qt-dab file recorded from the Airspy. For this case, qirx offers the 3Msps sampling rate.

**Comment by andimik** [comment]
Oh I see, let me try to suggest Jan to replace the record button from (currently) sdr to xml (which is only accessible in the device menu) ...

**Comment by softsyst** [comment]
Closing it. If anyone thinks it should be re-opened, please do so.
