### ISSUE TITLE
Renaming receivers

### ISSUE THREAD

**Issue by WIHDIA** [softsyst/qirx_issues#42]
I would be user friendly if the receiver name could be changed. E.g. receiver 1 into DAB-RTL or receiver 2 into ADS-B ....

73

Herman

**Comment by softsyst** [comment]
Thanks, Herman, for this useful suggestion. I'll check the effort.

**Comment by softsyst** [comment]
Herman, if you could occasionally make a short comment if the 4.01 brings what you had in mind, I could close this one (or not).

**Comment by WIHDIA** [comment]
Perfect for me.
