### ISSUE TITLE
Widgets

### ISSUE THREAD

**Issue by WIHDIA** [softsyst/qirx_issues#45]
Hi Clem,

My configuration as in [this picture](https://live.staticflickr.com/65535/52264523792_a0610d641e_k.jpg). 

After a restart the Audio widget is always 'on' even if another widget was so after closing a previous session. Is that the way it should be?

73

Herman
[My logblog](https://wijnants.info/fmdx/)

**Comment by softsyst** [comment]
Herman,

a very quick inspection shows it's not a feature, but a bug. Thanks for reporting. Will check it.

73,
Clem

**Comment by softsyst** [comment]
Fixed in V4.0.2, hopefully.

**Comment by softsyst** [comment]
No negative comments. I close it. If necessary, please re-open.
