### ISSUE TITLE
Incorrect data in UK Ofcom TII database

### ISSUE THREAD

**Issue by mrwish7** [softsyst/qirx_issues#46]
I recently updated the TII database with the spreadsheet from the previous issue regarding problems with the Ofcom database. (issue #39 )

However, the new data seems to be worse unfortunately. This isn't a problem with QIRX but rather a problem with erroneous data provided by Ofcom in their TX Params spreadsheet for DAB.

I now find a lot of TII codes are not shown on the map because the data is wrong. For example -

Ridge Hill (35 16) - in the Ofcom data/the QIRX XLS this is now listed as 28 0, which is incorrect.
Churchdown Hill - all muxes in the Ofcom data are listed as 27 17, whereas in fact both BBC 12B and Gloucestershire 10C are still 35 17.

I've found various other transmitter codes are missing/incorrect when I've received other multiplexes due to tropospheric ducting, e.g. NE Wales 10D, Derbyshire 10B, Nottinghamshire 12C, and others.

Is there a way we could optionally disable the Ofcom database for QIRX? All of the incorrect codes I have encountered are correct in the FMList/DABList database, so I would rather just use the data from that if possible.

Thanks, and thank you for the excellent software!

**Comment by softsyst** [comment]
Thanks for your input. 

I already have heard of the increasingly bad quality of the Ofcom data. The intent in using Ofcom as an "official" information was triggered by the expectation of the most possible accurate data, which obviously is no longer the case.

Thus, I will estimate the effort to switch between Ofcom and the DABLIST.
Perhaps not for the coming version, but it will stay on the agenda.

**Comment by softsyst** [comment]
Realized in V4.0.2

**Comment by softsyst** [comment]
I close this one, as it is realized.
