### ISSUE TITLE
Frequency won't change after a scan - QIRX 4.0.2

### ISSUE THREAD

**Issue by WIHDIA** [softsyst/qirx_issues#48]
Ending a scan the frequency in the device section (top left) stays on the frequency of the first scanned mux, no matter whan other mux you tune to. Small manual change in the frequency/device widget fixes this bug.

73

Herman

**Comment by softsyst** [comment]
This will be fixed in the next version.

**Comment by softsyst** [comment]
Fixed in 4.03. I close it.
