### ISSUE TITLE
Version 4: Re-enter licence after re-install or upgrade

### ISSUE THREAD

**Issue by andimik** [softsyst/qirx_issues#49]
When a user updates the software (in my case from 4.0.1 to 4.02) the licence key needs to be entered again. Seems the installation procedure overwrites the licence information somehow.

I own a lot of paid software, but they don't show this behaviour.

**Comment by softsyst** [comment]
I understand your comment as a suggestion that it should not be necessary to re-enter the license key after a re-installation of the software.
The installation procedure is not "license-aware".

The current procedure is the licensing policy. For instance, in contrast to most other paid software, it does not require registering, signing-in, using a password etc., to keep it as simple as possible. The only necessary "real-world" item is a valid email address in combination with an (arbitrary!) name.

At user's site, the license key together with the machine id is stored in the config file. After a re-installation, it only must be re-entered in case the config file has been deleted as part of the install procedure. Thus, re-entering it is **not generally necessary**. And the license key is not lost, as the old config file is backed up.

A "lot of other software" use a completely different licensing scheme, often based on encrypted registry entries. Qirx does not use the registry at all, for very good reasons.

But following your argument, the only property from where the server could find the license key would be the machine id. However, this is a four character string which is not guaranteed to be collision-free. Thus, retrieving the license key from it could be ambiguous. I very much would like to avoid it.

**Comment by softsyst** [comment]
As no action is planned on the issue, I close it.
