### ISSUE TITLE
Centre the map automatically when GPS mouse is connected

### ISSUE THREAD

**Issue by andimik** [softsyst/qirx_issues#50]
The default position is near Frankfurt/Main. In case a user connects a GPS mouse, the map should centre to the current position without user action, I suggest.

![grafik](https://user-images.githubusercontent.com/24510556/187016759-ee7f02bc-b559-447a-941b-1e73e675df1e.png)

**Comment by softsyst** [comment]
Realized in 4.03. I close it.
