### ISSUE TITLE
Any TII detection for Bavaria DAB+ networks

### ISSUE THREAD

**Issue by Lukas-CZE** [softsyst/qirx_issues#54]
Dear friends,

I have a rather interesting problem. Relatively recently, the TII code detection stopped working for me with the QIRX 4 software, but this ONLY applies to Bavarian networks such as Bayern, Oberpfalz, Oberfranken, Niederbayern, etc., for example Ingolstadt or the BDR Test multiplex are identified. Outside of Bavaria, all radio networks are now without problems. As I noticed, one of colleague already solved a similar problem here, but he did not see the TII code for all of the DAB+ multiplexes. This is not my case.

In addition to the new version of QIRX 4, I use the older software QIRX 2, because the Czech multiplex operator RTI cz is better identified here. Could this be the problem? But it is strange that this situation only happens at Bavarian multiplexes...

**Comment by softsyst** [comment]
- Did you check the SHA-1 hash of your downloaded .msi file?
- Please upload a raw file somewhere (e.g. dropbox) for verification, and post the download link here.

Thanks.

**Comment by Lukas-CZE** [comment]
As I see, problem is fixed now. I uninstaled both version, restart computer and instaled only QIRX 4.0.3 and I see TII code for Hoher Bogen and Einondriegel on channel 11D. It is luck we have a little bit good condition so Bayern mux works now. I close this problem. Thank you very much for cooperation. Previous discusion helped me very much. :)
