### ISSUE TITLE
Connecting to RTL_TCP running on Raspberry Pi

### ISSUE THREAD

**Issue by mrwish7** [softsyst/qirx_issues#57]
I may be being stupid here, but I can't seem to get QIRX to connect to rtl_tcp running on another machine (Raspberry Pi 4) on my local network.

On the Raspberry Pi I have rtl_tcp built from source and running with the IP address -

rtl_tcp -a (Pi local IP address) -p 1234 -d 0

In QIRX, for receiver 2 -

Start and stop are unticked, remote starter port set to 0 to bypass. IP is the Pi's IP address, port is 1234.

<img width="804" alt="Screenshot_20221222_170242" src="https://user-images.githubusercontent.com/37659188/209187970-64339bcf-f608-484e-b1eb-f573b6d4d890.png">

When I then click play to start the connection for receiver 2, I can see the connection happening in the server log on the Pi, but in QIRX I get the error that connect to (Pi IP address):1235 failed after 1 attempt.

<img width="272" alt="Screenshot_20221222_170409" src="https://user-images.githubusercontent.com/37659188/209188273-7a7aeb63-0e2e-4b62-a95d-ab711b6f3d57.png">

It seems like port 1235 is meant to be for control commands, but I can see no reference to this in the Linux version. Am I missing something? I have tested SDR#, and that manages to connect successfully to the remote rtl_tcp instance on port 1234 on the Pi.

Thanks,

Adam

**Comment by softsyst** [comment]
Hi Adam,

no, don’t worry, you’re not stupid. It’s all my fault. The old rtl_tcp connection does currently not work any more, as the rtl2_tcp connects a little differently. It requests first all available devices, and then let the user select one. As far as I know, there is no version for Linux yet for the rtl2_tcp. 

I see that this is not optimal, as the Raspi lends itself very well for a remote frontend.
I’ll see if I can do some workaround to make it work again. Maybe in the coming weeks.

Clem

**Comment by andimik** [comment]
> As far as I know, there is no version for Linux yet for the rtl2_tcp.

It's working on the raspberry. Just have successfully compiled https://github.com/old-dab/rtlsdr 

# Qirx settings

![grafik](https://user-images.githubusercontent.com/24510556/209585879-7609d8f8-30ec-4e0c-a682-ea770b095de4.png)

# Raspberry console
```
./rtl2_tcp -a 192.168.43.72 -p 1234 -d 0
rtl2_tcp, an I/Q spectrum server for RTL2832 based DVB-T receivers
Version 0.9.6.5 for QIRX, Dec 26 2022

listening on port 1234...
listening on port 1235...
client accepted!
control client accepted!
request all serials
```

BTW: 

a) Tuning to another channel takes a while, although Qirx already shows the new channel
b) I have lots of dropouts at the audio via WiFi (hotspot with my mobile), but this is also a problem with rtl_tcp and DAB Player, so please try via LAN

**Comment by mrwish7** [comment]
Thanks Clem @softsyst , and thanks @andimik -

I've just compiled rtl2_tcp from that source on the Pi and can confirm that it works very well. I find the channel tuning to be quick for me, and the reception is very stable (Pi4 connected to wired network, Windows laptop running QIRX connected to Wifi.)

**Comment by softsyst** [comment]
Thanks to both of you for this excellent news! However, all the credit goes to @old-dab aka @Oldenburger. It's his creation.
Time for me to re-activate my (a little rusty) Linux!
