### ISSUE TITLE
File open dialogue misses xml files

### ISSUE THREAD

**Issue by andimik** [softsyst/qirx_issues#59]
Although Qirx supports its own xml file header (see https://qirx.softsyst.com/RawXmlHeader ), the file open dropdown menu `Raw files (*.raw;*.sdr;*.txt)`does not show `*.xml` and `*.uff` files, therefore, you need to switch to `All files (*.*)`

![grafik](https://user-images.githubusercontent.com/24510556/209566437-a4fecd88-e445-4055-ad80-d83651a975bc.png)

**Comment by softsyst** [comment]
The .sdr file is not a file extension produced by qirx. Qirx writes only .raw files.

The .xml extension is not included, as usually the extension .xml is used for a xml file and not for a raw file containing some xml data, to avoid confusion (as it happened with me when processing some ODR produced MOTs). And .uff files? No idea whether there are apps using them as raw files. I never saw one. 

Currently, I hesitate to include this request into the queue.

BTW, for replaying raw files it might be more convenient to use drag'n drop and drag them on the Frontend pane. There, all files are accepted, and it is much faster than the selection via the File Dialog.

**Comment by andimik** [comment]
> And .uff files? No idea whether there are apps using them as raw files. I never saw one.

This is the standard extension for these xml-files in Qt-DAB. See https://github.com/JvanKatwijk/qt-dab/blob/682dfbf3d744a134eafe0c01c74bef3fcb5a0454/qt-devices/rtlsdr-handler-win/rtlsdr-handler.cpp#L483

**Comment by softsyst** [comment]
As no action is planned on the issue, I close it.
