### ISSUE TITLE
APRS decode

### ISSUE THREAD

**Issue by esplien** [softsyst/qirx_issues#6]
I have been analyzing APRS-spectrums to estimate deviation and AF-spectrum to see whether pre-empasis is in use or not. When AF-spectrum is properly set, it is possible to see whether the tones have equal amplitude or 2200 Hz is ca 6dB higher than 1200Hz or not. 

There are some challenges though, 
1. to capture spectrums at the right moment
2. to identify the source of the signal 

I can get one spectrum or the other, but I cannot identify digipeater or mobile APRS, and there is some more delay from a FM-radio to RTL, so identification of spectrum would be very helpful
![no pre-emphasis_ld2rk](https://user-images.githubusercontent.com/86978465/124505614-30fdbe00-ddca-11eb-8b2d-9262b6c0de81.jpg)
![With pre-emphasis](https://user-images.githubusercontent.com/86978465/124505620-31965480-ddca-11eb-8c8b-0f6a7deb5a3f.jpg)

**Comment by softsyst** [comment]
Not sure if I get you right. What do you want to achieve? Do you want this feature to see whether de-emphasis is switched on or not? If I implement the de-emphasis as you suggest, then some flag would be on the GUI indicating if it's switched on.

**Comment by esplien** [comment]
Hii,

The history of pre/de-emphasis is some decades old. It was found in aerly BC days, that the Audioresponse turned not out as flat and noiseless as one once thought. Then a smart guy got the idea, if we changed the tx-audio response by increasing amplitude of wanted higher freq and reversed it in the receiver, one couldget a flat system Audio response With less hisss-noise

What I want to achieve is the possibility to see if and to what extent pre-emphasis is implemented by analysing the relative amplitude of 1200 and 2200 Hz, which by 750us should be ca 6dB higher at 2200.The purpose of pre-emphasis is to increase S/N at higher frequencies, and the de-emphasis reduces the higher AF eg 2200 by 6dB and in sum we get flat AUDIO-response, and the most annoying highfreq noise will also be reduced by at least 6 dB.

The spectra should for ease of analysing be standing still, ie.e Max-Hold function by a button.

For Identifying the transmitters APRS-callsign would be needed, because the delay between a -FM receiver and qirx.

I want to be able to capture the RF and AF-spectrum and Connect it to a transmitter by its callsign, so that Iknow if  were lookng on a digipeater or i.e. a mobile ham and seethe effect of pre/de-emphasis.
For me possibility of turning on and off de.emphasis is ok, but an indicator-lightmight be useful for some. 

And least (for now) but probably not last, even FM RDS and DAB PI will be useful when receiving FM or DAB.

73 gl gn de
Espen
LA1RQ

Sendt fra E-post for Windows 10

Fra: softsyst
Sendt: mandag 5. juli 2021 kl. 23:32
Til: softsyst/qirx_issues
Kopi: esplien; Author
Emne: Re: [softsyst/qirx_issues] APRS decode (#6)

Not sure if I get you right. What do you want to achieve? Do you want this feature to see whether de-emphasis is switched on or not? If I implement the de-emphasis as you suggest, then some flag would be on the GUI indicating if it's switched on.

**Comment by softsyst** [comment]
From your description it seems to me not to be a feature of its own, but a combination of de-emphasis and max-hold. Thus, I close it for now.

**Comment by esplien** [comment]
Clem,

Sorry I have not been Clear; I meant two features:

1. MaxHold for 
a) analysing RF and 
b) analysing AF
2. De-emphasis off or on.


73 de
Espen
LA1RQ

Sendt fra E-post for Windows 10

Fra: softsyst
Sendt: tirsdag 6. juli 2021 kl. 17:16
Til: softsyst/qirx_issues
Kopi: esplien; Author
Emne: Re: [softsyst/qirx_issues] APRS decode (#6)

From your description it seems to me not to be a feature of its own, but a combination of de-emphasis and max-hold. Thus, I close it for now.

**Comment by softsyst** [comment]
Espen,

I had understood this in the way you are mentioning it here. It's the two features:
- Max-hold for RF and AF
- De-Emphasis
These requests are covered by #7 (Max Hold for both spectra) and #4 (De-emph).

Best,
Clem
