### ISSUE TITLE
Prepare TII log file headings for spreadsheet import

### ISSUE THREAD

**Issue by andimik** [softsyst/qirx_issues#60]
The word "Strength" (and the - in the next row) in the TII log file
![grafik](https://user-images.githubusercontent.com/24510556/209569928-2d23ac46-1217-4dd3-aedc-2dbe08e7a9c5.png)
is too long, so the columns on the right get a wrong a header, therefore, I'd like to propose to  

- remove the 2nd line ending
- remove two tabs en suite
- use longer/shorter headings

For example 
```
	QIRX 4.0.4.0    TII Logger started at 2022_12_26 16:45:29 UTC
	All times are in UTC!

Date/Time		Selector	Ensemble-Id		SNR	Threshold	Pattern	Main Id	Sub Id	Strength	km Abs.	km Rel.	Bearing	Own Lat	Own Long	Own MSL	Valid
---------		--------	-----------		---	---------	-------	-------	------	--------	-------	-------	-------	-------	--------	-------	-----
2022_12_26 16:45:30Z 	12C		9400 (SLO DAB+ R2 W   )	10.8	0.15		0x1b	2	10	0.882	66.9	0.0	115.2	46.55004	13.74537	 566	True

2022_12_26 16:45:31Z 	12C		9400 (SLO DAB+ R2 W   )	10.5	0.12		0x1b	2	10	0.789	66.9	0.0	115.2	46.55005	13.74536	 567	True

```

should become this afterwards

``` 
	QIRX 4.0.4.0    TII Logger started at 2022_12_26 16:45:29 UTC
	All times are in UTC!

Date and Time       	Chn	Ensemble-Id and Label  	SNR	Thrsh	Patt	MId	SId	Stren	km ab	km rel	Bearing	Own Lati	Own Long	OwnMSL	Valid
--------------------	---	-----------------------	---	-----	----	---	---	-----	-----	------	-------	--------	--------	-------	-----
2022_12_26 16:45:30Z 	12C	9400 (SLO DAB+ R2 W   )	10.8	0.15	0x1b	2	10	0.882	66.9	0.0	115.2	46.55004	13.74537	 566	True
2022_12_26 16:45:31Z 	12C	9400 (SLO DAB+ R2 W   )	10.5	0.12	0x1b	2	10	0.789	66.9	0.0	115.2	46.55005	13.74536	 567	True
```

which can be imported into a spreadsheet (Excel, Calc), see screenshot below.

Remark: `.` and `,` have to be changed in order **not** to get 10.Aug instead of 10.8 for SNR value, but this is not related to Qirx.

![grafik](https://user-images.githubusercontent.com/24510556/209569521-754ef6eb-4190-4222-8928-631a7f1a5f8b.png)

**Comment by softsyst** [comment]
Certainly a very valid comment, in particular thanks for the suggestion of the shortened header. Will give it a try.

**Comment by softsyst** [comment]
Realized in 4.0.5
All entries are now separated by one "tab" character. This should be now handled correctly when importing into Excel.

**Comment by softsyst** [comment]
No further comments received. I close this one.
