### ISSUE TITLE
Background colour for Audio (ok %) is grey instead of red

### ISSUE THREAD

**Issue by andimik** [softsyst/qirx_issues#61]
When the reception is too bad, the background colour for `Audio (ok %)` should be red instead of grey.

# actual
![grafik](https://user-images.githubusercontent.com/24510556/209571087-d469e6a9-eebd-4782-ac36-d6d6822b0f12.png)

# proposed
![grafik](https://user-images.githubusercontent.com/24510556/209571185-85cb3d8b-a43e-46d5-8248-6e8391ce4207.png)

**Comment by softsyst** [comment]
Good suggestion. I'll put it into the queue.
**Edit**: After investigation, I changed my opinion, see next posting.

**Comment by softsyst** [comment]
I investigated it, and I would like to leave it as it is:

The Audio field ranges from 0 to 100, coloring from"0" to "20" as red, and the rest yellow or green. However, this color is not filling the whole rectangle, but only the part of the rectangle which is shown. At "0" the rectangle has zero width, and therefore the rest is the total field having its default color, gray. Other, similar fields like the FIC never reach the zero with an actively possible reception.

Thus, this is consistent with all other fields, except the "BER", as those are always fully filled.
Here is an example with a very low percentage of "Audio ok":
![image](https://github.com/softsyst/qirx_issues/assets/51386375/442a2824-f2c2-4a2d-8b1b-a7b37a0519d5)

**Comment by softsyst** [comment]
I close this one. I will not work on it, and no more comments arrived.

**Comment by andimik** [comment]
You have already commented it, so there was no reply necessary.
