### ISSUE TITLE
First tab remains in main document group on last received channel

### ISSUE THREAD

**Issue by andimik** [softsyst/qirx_issues#63]
When you switch from an active DAB channel (like 8A in the screenshot) to an inactive one (like 5A in the screenshot), the first tab in the main document group remains on the last received channel (= it is not reset).

I don't know if this is a feature or bug.

![grafik](https://user-images.githubusercontent.com/24510556/209572502-c63f2123-a4a1-4eb7-820d-4781df6509f1.png)

BTW: It always contains an unnecessary additional line with empty checkboxes, see screenshot.

![grafik](https://user-images.githubusercontent.com/24510556/209572688-9ed9c98f-aaab-4395-8844-d6c85043e321.png)

**Comment by softsyst** [comment]
This (uncomplete clearing on changing to inactive mux) was also an issue for the other DAB tabs. There, it should as well be fixed in V4.0.5
