### ISSUE TITLE
Licence key storage

### ISSUE THREAD

**Issue by andimik** [softsyst/qirx_issues#65]
The licence key for v4 is stored in `%localappdata%\qirx4\qirx4.config`.

```
  <Authentication>
    <Key value="[...]" />
    <MachineCode value="[...]" />
  </Authentication>
```

If a user needs to reset the config by deleting/renaming this file, the licence key needs to be re-entered in Qirx.

So I suggest to store this XML tag in a separate file other than `qirx4.config`

**Comment by softsyst** [comment]
This would only postpone the problem, and complicate the software. It is the responsibility of the user to keep its license code, as usual btw. And if someone really loses the code, a short email is sufficient. This (email necessity) happens every now and then when a new machine binding becomes necessary, for transferring the code to another machine. 
As already discussed if I remember correctly, when letting the installer create a new config, the old one is back-upped.

**Comment by andimik** [comment]
> the old one is back-upped

Yes, correct, therefore, I'll close.
