### ISSUE TITLE
About Qirx Window too large - no OK button visible

### ISSUE THREAD

**Issue by andimik** [softsyst/qirx_issues#68]
The new additional (and unnecessary) lines in the "About Qirx" window prevents me from clicking on OK. This only happens right after the start when the program asks for the licence key.

![grafik](https://user-images.githubusercontent.com/24510556/211662640-7f70876a-1380-46cf-aab8-4b2b1e750866.png)

If you close the window with X, then the following "About Qirx" windows have a different size, and you are able to click on ok.

![grafik](https://user-images.githubusercontent.com/24510556/211663373-31e556cb-20d7-4dfb-9d40-5f0e4fb3f64e.png)

My resolution is 1366x786, which is quite common for Lenovo laptops.

**Comment by softsyst** [comment]
Which lines are not necessary in your opinion?

**Comment by andimik** [comment]
The empty lines before and after the three buttons.

And due to the fact that the version list has an own scroll bar, it could be a bit smaller in the height.

**Comment by andimik** [comment]
But you should just investigate, why the button is not shown the first time, but the second time it is visible, although it is the same window.

**Comment by softsyst** [comment]
Ok, the About Box should be fully visible also on a smaller screen. This will be fixed. The empty lines make the layout better comprehensible. It is a matter of taste.

**Comment by softsyst** [comment]
From V4.0.6, the About box should be fully visible also on a screen with a height of 768. I close this now. If you see any issues, please feel free to re-open.
