### ISSUE TITLE
Missing data on 1st tab

### ISSUE THREAD

**Issue by andimik** [softsyst/qirx_issues#69]
If the mux is not 100% errorfree, there is missing data on the 1st tab. Seems the table is generated only once with a (too short) timeout.

See "Radio Aktual Kum", I can play this service (and it appears in the list on the left), but its info is missing on the right.

![grafik](https://user-images.githubusercontent.com/24510556/211664857-f4f170e1-20d8-4d37-8851-d07b134db0ab.png)

**Comment by andimik** [comment]
It even can stay empty under certain circumstances ...

![grafik](https://user-images.githubusercontent.com/24510556/211665591-994543b8-4cab-43ac-a61b-8e5eb4faac08.png)

**Comment by softsyst** [comment]
Right mouse click: Refresh command repairs it. Therefore there is no continuous update necessary.

**Comment by andimik** [comment]
No, I don't agree. In case there are discrepancies between the left list and the right table, the program should update, not the user.

This is like `if right != left then refresh`...

**Comment by softsyst** [comment]
As no action is planned on the issue, I close this.
