### ISSUE TITLE
Max Hold - function request

### ISSUE THREAD

**Issue by esplien** [softsyst/qirx_issues#7]
Sometimes it is very useful to have a max-hold function on both RF and AF spectrums.

**Comment by softsyst** [comment]
At last, realized in the 4.0.8! However, RF only currently.

**Comment by esplien** [comment]
Hi Clem, 

sorry for late answer from me..
I think it looks nice with the new MAX-HOLD function, but I can't find MAX HOLD for the Audio spectrum? 

I also like the automatic frequency correction, but should it really vary from correction to correction within seconds? Always increasing, from -0.077 to more than -2.5

 

73 de


 

Espen Lien
 

    På tirsdag 25. april 2023 kl. 18:06:24 CEST skrev softsyst ***@***.***> følgende:  
 
 


At last, realized in the 4.0.8!

**Comment by softsyst** [comment]
Hi Espen,

what would be the use for the Max-Hold in an audio spectrum? I cannot see it. If there is a real use, of course I can re-open the issue.

For the automatic frequency calibration, yes, it should vary within seconds (15s, to be exact). The change must not be too high, otherwise it would cause a re-sync in DAB what should be avoided. Currently it re-syncs once or twice at warmup, not more often. DAB re-syncs already with changes of about 20Hz. You might try it yourself by un-checking the Automatic Fine Frequency correction, and moving the slider.

In steady temperature state, it does not increase always but varies around a mean value. The dongles more (they are accurate to 7Hz), their threshold for re-calibration is 10Hz, the RSPs less, as they are accurate to about 0.5Hz, their threshold for re-calibration is 0.7 Hz. And the Airspy not at all, as it got no "ppm" correction possibility in its API.
And - after all - if you don't like it you could un-check it. The checkbox state is persisted.

73
Clem

**Comment by esplien** [comment]
Hi Clem,

My use for max hold in af-spectrum is diagnosing low coverage of APRS.
It is known that some combos of radio and APRS units are hard to build with preemphasis depending on where the APRS has to be connected in the radio.Available transceivers has 750us pre/de-emphasis built in, from the mic input and to audio output.


 There are even some hardnecks believing that pre/de-emphasis destroy audio quality, but pre/de-emphasis in reality can increase coverage by a factor of 2 (6dB/decade 1kHz-2kHz).

Regarding the v.4.08 I have so far the impression that it is more stable with Airspy than v.3.

Thanks for your explanation on the automatic frequency correction, I like it, but unfortunately I bought the wrong rx..  I will look more into it and maybe buy another box…


//Espen 
Sendt fra min iPhone

**Comment by softsyst** [comment]
Thanks for your explanantion, Espen. You had mentioned it already before, which I had missed.
I reopen the issue.

**Comment by softsyst** [comment]
Hi Espen,

Collecting the audio max values should work in the V4.0.9. Please check if it is ok for you.

**Comment by esplien** [comment]
Hi Clem,thanks for the update! 

It v.4.09 works well now also with maxhold. But it looks like something (noise?) sometimes lift the spectrum to max for parts or all AF-band:


I am sorry it took som long to test it, but I had some issues with the desktop Workstation regarding change of harddisk, and evt Installation of Linux, for EladRemote to run my rig at holiday qth remotely. It seems like an update of Win10 from 19.january blocked serial connections via virtual serial ports to WSJTx, and the developer has been working on another way to pass serial from Cygwin-linux to Win10...
On the next picture you can see why I wished for MaxHold also in AF spectrum. The received APRS signal obviously has no pre-emphasis.. If it had, the 2200 Hz component would have abt 6dB higher level than 1200Hz, and so increase the coverage by 2 times, provided the receiver also had de-emphasis...

Below the spectrum showing how a receiver with 750us de-emphasis would receive APRS without pre-emphasis. 


But I am a bit worried about the frequency accuracy on AF: it looks like 1200Hz is about 100Hz below and 2200Hz is 100Hz above ...??
2.Regarding the Channel Power calculation, I found an article from R&S describing how (they?)  calculate Channel Power, 3 possible solutions: Maybe the 3. methode 
the integrated bandwidth method
could be possible to realize? Of course one would have to establish the real power level of full scale (FS) and calibrate the software with acutal SDR-rx...

Understanding Channel Power Measurements - Channel power

| 
| 
| 
|  |  |

 |

 |
| 
|  | 
Understanding Channel Power Measurements - Channel power

Get an introduction into what channel power is and the three most common ways that channel power is measured usi...
 |

 |

 |




 
Best regards / 73 de
LA1RQ

 

Espen Lien
 

    På torsdag 29. juni 2023 kl. 23:10:49 CEST skrev softsyst ***@***.***> følgende:  
 
 


Hi Espen,

Collecting the audio max values should work in the V4.0.9. Please check if it is ok for you.

**Comment by softsyst** [comment]
Hi Espen,

thanks for your feedback, and the remark that you are now satisfied with the max-hold of the audio. Thus, I will close this issue, at last.
Sadly, no pictures in your posting arrived here. So I cannot comment about them. Also the references to the R&S paper were not readable, only vertical bars.

One remark though: You are worrying about the accuracy of the audio frequency measurement (didn't we have this in the past already?). Therefore, I just made a measurement with NFM at 145.3MHz, 4kHz modulation bandwidth, modulated with two sine tones, 1200 and 2200, both equal amplitude, all coming out of my Agilent (Rubi controlled). 
Please don't worry, although the audio resolution is not too high, the two tones show the correct frequency being well in the accuracy of the FFT resolution. The receiving dongle has been calibrated. Deemphasis was off.

![DualTone_1200_2200_2](https://github.com/softsyst/qirx_issues/assets/51386375/b07533f5-bdd7-4846-916d-ad5a27bf9b84)

Maybe you should check your equipment.

And, a last request:
Please be so kind and do not mix several problems into one issue. This makes the tracking rather difficult. However, please feel free to open new issues (new features, bugs, enhancements, remarks) any time as you think it appropriate.


73,
Clem
