### ISSUE TITLE
SPI from OpenDigitalRadio SPI encoder not decoding

### ISSUE THREAD

**Issue by nickpiggott** [softsyst/qirx_issues#71]
Hello,

The support for SPI (EPG) in qirx is brilliant, very very helpful.

Along with Ben Poor, I maintain the [open source SPI generator](https://wiki.opendigitalradio.org/How_to_configure_SPI_(Service_and_Programme_Information)_for_ODR-DabMux), and I also use it to create SPI services on small scale DAB multiplexes in the UK. I've noticed that QIRX doesn't recognise the service - it appears in the service listing as a PACKET_DATA application of type MOT_OBJECT - but it doesn't appear in the EPG tab and no station logos are shown.

A RAW file recording of the Bristol multiplex is [here](https://drive.google.com/file/d/1KxxID9k11oVQMxJVvIauFv-EZs6U5Xb5/view?usp=sharing).

In my own qirx install, I can see the SPI folder for the mux (E1C1D3) being created, and folders for each service in the SPI, but no logos within those folders. Only one station provides PI (C897), and I can see the PI XML documents being decoded but not used.

The Open Source generator has been checked by other implementers, and we've not had any feedback to say it's non-compliant, except potentially for a ambiguity on how the default language is binary encoded.

It would be great to see if we can get it decoding in qirx, or if you can spot why it isn't being decoded.

Nick

**Comment by softsyst** [comment]
Thanks, Nick, for this input. I'll check it and will get back asap.

Clem

**Comment by softsyst** [comment]
I figured it out. There were two issues:

The first one was my bad. You generate the binary info which is then converted to xml in a different sequence than all others which I saw until now. I only checked the first file, didn't find the "serviceInformation" tag, and left the scene with an error.  I am really wondering why this (rather serious) bug did not show up earlier.

The second perhaps as well, don't know. 
You write in the EPG behind the time a "UTC" trailer which I didn't expect until now. Never seen it before. Now I accept it, but do not make anything with it. The result shows the following screenshot:
![image](https://user-images.githubusercontent.com/51386375/214867143-729e6100-0119-4a56-aed6-60ab288bf970.png)

So, please check whether it's ok that not all icons are sent, as some services do not show logos, And, please check whether it is ok that the station "Gaydio" is the only one transmitting an EPG.

I also noticed the "Gaydio" sends links to pictures (artists?). How is your intent to present these? I find it a good feature, not seen elsewhere (or it went unnoticed).

Regards,
Clem

**Comment by softsyst** [comment]
Sorry, I had closed it unintendedly.

**Comment by nickpiggott** [comment]
That's great, very good fix.

* Logos - those are correct. The missing stations don't have a registration with RadioDNS (which is how we source the logos)
* Only Gaydio is currently sending PI, so this is also correct
* You can specify links to a visual asset in a <programme> element - often this is used to make the schedule item clickable to a view that shows the programme title, the programme image and the programme synopsis. There's an example view [here](https://photos.app.goo.gl/XfbNegDLGnA1WeoC9). (Not a great photo, sorry).

**Time Handling**

I didn't understand your observation on the time attributes? We set LTO flag (b19) if the local time is not UTC, and then the local time offset value is in 8 bits starting at b32 (or b48 if UTC event time is in the long format).

The programme schedule times for Gaydio are correct, I think because at the moment, the UK is on UTC. It may be wrong in the summer when the UK is at UTC + 1. In those times, for the example of Gaydio, the breakfast show would be encoded as 06:00 (UTC) + 01:00 (time offset) = 07:00 local time.

I have just looked at our timepoint encoding, and I think there's a bug in it, because I see a missing b20 which should be Rfa 0. So don't fix anything your side yet, it may be on our encoder.

**Comment by nickpiggott** [comment]
Hello - I was incorrect. The UTC time encoding from b20 onwards is correct; b20 will be 0 or 1 depending on the accuracy of the time, and then b21-31 (short) or b21-47 (long) contain the UTC time.

Then the offset time is added to the UTC time to find the local time to display the programme time at.

But in this encoding, LTO (b19) should be 0 because currently the UK is in UTC.

**Comment by softsyst** [comment]
Sorry about the "UTC" confusion. I add the "UTC" suffix in the xml myself.

I just checked it in the decoder, and it should be according to the standard. MJD gives UTC, and the LTO the offset in units of half hours, positive or negative. In addition, the short and long format. 

In the code where the display is generated (interpreting the xml), I did not expect the "UTC" as here it was the first time I met it. But I'll add something to indicate UTC (in the DAB time I use the old Z for "Zulu", ignoring the LTO altogether), ignoring the special UK case (in winter) where UTC is identical to local time.

For your solution, IMO it would be the better solution to set the LTO bit, and leave the local offset to zero.

Thanks also for the link to the visual asset.

**Comment by softsyst** [comment]
Please check whether it works ok in 4.0.6 or 4.0.7. Thanks!

**Comment by nickpiggott** [comment]
Is that available for download now?

**Comment by softsyst** [comment]
Yes, it is.

**Comment by nickpiggott** [comment]
Hello

v.4.0.7 - I can confirm station logo decoding is operating correctly

![image](https://user-images.githubusercontent.com/11558362/220058203-24cd1b61-b795-49c4-8338-b582558b975d.png)

and programme schedule information too

![image](https://user-images.githubusercontent.com/11558362/220058773-0356c1cb-d9b5-42ff-b958-fa2bdf5d386a.png)

Thanks for the update, very helpful.

**Comment by softsyst** [comment]
Thanks, I close this one.
