### ISSUE TITLE
4.0.6 TII codes retained on new empty mux

### ISSUE THREAD

**Issue by WIHDIA** [softsyst/qirx_issues#76]
When switching from a mux with lots of TII codes shown to an empty mux, these TII codes are retained. There are no
retained on the map.

![afbeelding](https://user-images.githubusercontent.com/53539654/219717410-c6986ee6-7247-4c55-9851-4b1ef90b9b4a.png)

73
Herman

**Comment by softsyst** [comment]
Thanks, Herman, for reporting!
A seeming "improvement" caused this unexpected side effect. Will be repaired soon.

73,
Clem

**Comment by softsyst** [comment]
4.0.7 containing the fix is online.

**Comment by WIHDIA** [comment]
Hi Clem,
Works well now.

73
Kind regards


Herman Wijnants


    Op zondag 19 februari 2023 om 01:49:45 CET schreef softsyst ***@***.***>:  
 
 


4.0.7 containing the fix is online.

**Comment by softsyst** [comment]
Thanks, Herman.
I close this one.

73,
Clem
