### ISSUE TITLE
Hang when changing mode directly to ADS-B

### ISSUE THREAD

**Issue by esplien** [softsyst/qirx_issues#8]
Spectrum and Waterfall does not start receiving when I change directly from i.e. NFM or AM (Airband). The playbutton is dark, no reaction. But decoding seems to work...

**Comment by softsyst** [comment]
Could you describe step-by-step how I can reproduce the situation? With AM or NFM you need a sampling rate of 2048000, with ADS-B you need 2000000.

**Comment by esplien** [comment]
Hi,

Yes, I was receiving AM On 118.3, changed mode to ADS-B (without stopping). Decoding seems to work, but Spectrum and Wf stands still. The dialogue window explains the sampling rate, I click OK, no response, I minimize the qirx-window to find the dialogue still there, and I click ok again, dialogue disappears. When maximizing qirx-window, Spectrum and wf still stopped. 

This might be two issues, as the dialogue window sometimes is hidden behind qirx-window and sometimes visually over qirx-window, but gives no response. 
Either way, spectrum and wf is frozen.

//Espen 
Sendt fra min iPhone

**Comment by softsyst** [comment]
What you are trying to do is not the intended and described behavior: Please read  [**here**](https://qirx.softsyst.com/QIRXSetup3) and scroll to the Setup Dialog. There you read that for AM a sampling rate of 2048000sps is to be used, and for ADS-B a sampling rate of 2000000sps, which (quote) "**should not to be used for the other demodulators**". Thus, you cannot use AM and ADS-B without changing the sampling rate, on the same receiver. And to change the sampling rate you MUST stop in between.
Even if AM seems to work with 2000000sps sampling rate, there may be unexpected results. Same with other Demodulators like NFM or WFM.
One of the reasons for the multi-receiver feature was to have one rx for ADS-B, and another one for AM.

**Comment by esplien** [comment]
Hi Clem,

I have already noticed that ypou recommend to use sampling rate 2000000 for ADS-B and 2048000 for other modes. I understand that that is one good reason for having more than one  receiver. 

But the Message Box that appeared when I changed mode from AM (sampling rate=2048000) to ADS-B led me to believe that qirx changed the sampling rate automatically:




73 de
Espen
LA1RQ

Sendt fra E-post for Windows 10

Fra: softsyst
Sendt: onsdag 7. juli 2021 kl. 16:32
Til: softsyst/qirx_issues
Kopi: esplien; Author
Emne: Re: [softsyst/qirx_issues] Hang when changing mode directly to ADS-B (#8)

What you are trying to do is not the intended and described behavior: Please read here and scroll to the Setup Dialog. There you read that for AM a sampling rate of 2048000sps is to be used, and for ADS-B a sampling rate of 2000000sps, which (quote) "should not to be used for the other demodulators". Thus, you cannot use AM and ADS-B without changing the sampling rate, on the same receiver. And to change the sampling rate you MUST stop in between.
Even if AM seems to work with 2000000sps sampling rate, there may be unexpected results. Same with other Demodulators like NFM or WFM.
One of the reasons for the multi-receiver feature was to have one rx for ADS-B, and another one for AM.

**Comment by softsyst** [comment]
Hi Espen,

 

The automatic change of the sampling rate would be indeed a useful feature. However, I will not implement it automatically on change of a demodulator, for technical reasons. The problem with this automatism is that the Setup Dialog does not know anything about the indended demodulator. Thus, I am currently not sure if I can implement it with reasonable effort. 

However, you always have the possibility to check the actually used sampling rate on the GUI, in the "Connection" tab ("Sampling Rate SW"). 



 

In the case of your issue report, I assume that you tried to run AM with a sampling rate of 2000000. Running ADS-B with 2048000000 will usually not decode anything.

 

Sorry about this,

 

73,

Clem
