### ISSUE TITLE
Qirx 3.2.2: No audio in mode WFM (only noise) after upgrade to Windows 11

### ISSUE THREAD

**Issue by schluckspecht** [softsyst/qirx_issues#83]
Qirx 3.2.2: No audio in mode WFM (only noise) after upgrade to Windows 11. DAB works normally, but in case of WFM you hear only a strange noise like strong wind. The only possibility to avoid this problem is to start the program as administrator, not as a normal user, or to start it in a Windows 8 compatibility mode. For the 4.x versions I did not see it until now.

**Comment by softsyst** [comment]
No idea, also cannot test it here, as I have no Windows11 (and will not get one, currently).
AM/NFM the same?

**Comment by schluckspecht** [comment]
I found the reason, I did not see it immediately. When WFM starts, the bandwidth is set to 1 kHz. Of course, that does not work. Setting it to 150 kHz and everything is fine. Obviously during startup some files with the correct default values can not be read. 
For AM and narrow FM and DAB the bandwidth is correct.

**Comment by softsyst** [comment]
Ok, thanks for info!

**Comment by softsyst** [comment]
As it is clear what happened, I close it.
