### ISSUE TITLE
QIRX 4.0.8 AirspyR2

### ISSUE THREAD

**Issue by WIHDIA** [softsyst/qirx_issues#84]
Hi Clem,

I've been testing 4.0.8 with Airspy. AGC is still best OFF as it doesn't seem to work well. Manual Gain works a lot better.
With Airspy R2 the Gain DB is greyed.

Best regards,

Herman

[My logblog](https://wijnants.info/fmdx/)
Belgium editor of [fmlist.org](https://www.fmlist.org)

**Comment by softsyst** [comment]
The gain dB is greyed because the Airspies do not send the gain back. Normal behavior.

**Comment by softsyst** [comment]
I close this, no further input or comment.
