### ISSUE TITLE
RSP2 LNA State slider initial position

### ISSUE THREAD

**Issue by edd-cgfan** [softsyst/qirx_issues#86]
Hi Clem,

Thanks a lot for this new version.
Sometimes it is necessary to change the LNA State of my RSP2.
With version 4.0.8 I experienced that the initial position of the slider doesn't correspond to the saved and shown value.
After receiver start it looks like this:
![LNA_State_slider-initial-position_1](https://user-images.githubusercontent.com/49753409/235370999-4bd8ebb9-517d-4672-a563-bab9c8bc16d6.png)

When I first touch the slider with the mouse the value jumps to value 3 as can be seen here:
![LNA_State_slider-initial-position_2](https://user-images.githubusercontent.com/49753409/235371090-7f1fb7ee-e0c8-4362-a333-fac05e2f0a0b.png)

A change to value 6 looks then like shown here:
![LNA_State_slider-initial-position_3](https://user-images.githubusercontent.com/49753409/235371187-2a6ea07b-6f18-42d4-aebe-ead24883646e.png)

When setting the value to 8 and closing QIRX you can see that it is saved in the config file as 9 over here.
If you start now then the LNA Sate is initially set to 0:
![LNA_State_slider-initial-position_4](https://user-images.githubusercontent.com/49753409/235371821-2c3a1235-1c44-4676-89d1-7aa699b921aa.png)

Additional question:
Would it be to much programming effort to connect the slider with 2 of the arrow keys?

Best regards,
cgfan

**Comment by softsyst** [comment]
You are causing me headache: Your first remarks (and I notice very well: this time an issue, not a typo!) seems to be a bug, the second suggestion is an enhancement. If I tag it with "bug" and also "enhancement", it could be misunderstood! 
So I prefer "enhancement" (the left/right arrows) and (hopefully) fix the bug silently!

No worries, thanks for the input! 

Clem

**Comment by edd-cgfan** [comment]
> You are causing me headache...

Oh, sorry, that wasn't my intention.
Enhancement sounds great.
I look forward to getting the enhancement.

cgfan

**Comment by softsyst** [comment]
Can you please check it with the 4.0.9?
And - a friendly request: Please avoid mixing several issues in one thread, here the LNA Slider persistence and the keyboard operation. I would like to close this one if the LNA status persist is ok, and request you to open a new Issue for the keyboard operation (you could just copy and pasta your text). In that way it won't be forgotten.
Thanks!

**Comment by edd-cgfan** [comment]
Hi Clem,

Thanks for the new version.
Just checked the slider operation with my RSP2:
Works perfectly now.

cgfan

**Comment by softsyst** [comment]
Thanks for your fast response. I close it. Please see my remark above w/r to the keyboard operation. Feel free to open another issue for it. I'll have a look into it if having some more time.

Clem
