### ISSUE TITLE
SPI logo in the Service tab

### ISSUE THREAD

**Issue by edd-cgfan** [softsyst/qirx_issues#87]
Hi Clem,

This morning I got the chance to receive the 10A mux from Leipzig-Messegrund again, 105.6 km away, including SPI data.
I thought you might like to know how 2 logos are shown in the Service tab. They occupy too much space.
Is this the intended look?
![10A-L-Beatzz-ServicePic](https://user-images.githubusercontent.com/49753409/235508593-2c33685f-1dc9-4b9e-8ec1-ac7c28a9c5bf.png)
![10A-L-PSR-ServicePic](https://user-images.githubusercontent.com/49753409/235508618-16637835-db7c-49d2-bd9e-9a69d33a6756.png)

Here is zipped the content of the SPI folder for E01011:
[SPI.ZIP](https://github.com/softsyst/qirx_issues/files/11367353/SPI.ZIP)

And here is a link to a 1-minute raw file taped this morning:
[10A-L raw file](https://drive.google.com/file/d/1UGtxtaqrk7Vf0DLS7h2r1alr5EfGx6nY/view?usp=sharing) 

Best regards,
cgfan

**Comment by softsyst** [comment]
Hi cgfan,

No idea why the logos in your pictures are so pixelated, usually they are very clear. I have not the possibility to verify this ugly look here. (**Edited remark**: this is wrong, as cgfan provided the SPI directory content, see below).

I'll try to explain the "intended look". Look here (from your file):

![image](https://user-images.githubusercontent.com/51386375/235540720-8d847bbc-12e8-459a-b467-2ad571c0d59e.png)

The text in the small logos will not be readable even with a microscope. In contrast, the logo in the "Service" tab transports the message of the image. The text is crisp-clear. In this way one gets at least what the useless small logo intents to show.

Unfortunately, most services go the simplest and most boring way to repeat the logo in the slideshow. Probably the cheapest solution, fitting the content. However, some do it better and try at least to use the slideshow to show information. Pictures of the artists, weather info. There would be many possibilities.

Another example, not optimal, but they try at least to show something useful:

![image](https://user-images.githubusercontent.com/51386375/235541882-d45b17d5-f8b1-407a-b93f-2d7f6e185e9d.png)

No unreadable text in the small logo, the large logo shows text, perfectly readable, and the SLS shows one of the mods. Why not? Much better than most of the other crap.

So, nothing will happen here, I hope you got the intent.

Clem

**Comment by andimik** [comment]
I could not see an xml.

Let me guess: Qirx does not know which Logo to be displayed here and uses `C0BA2C87.png` (112x32) 
![FFF412FA](https://user-images.githubusercontent.com/24510556/235601840-32084125-1689-4851-908e-3e4364e06b8b.png)

instead of `A61F8F7C.png` (320x240)
![A61F8F7C](https://user-images.githubusercontent.com/24510556/235601850-1dc6fead-32c9-4bfd-93b5-6adb0dec77d9.png)

`C0BA2C87.png` is the small one.
![C0BA2C87](https://user-images.githubusercontent.com/24510556/235600680-6bdefae5-0f59-463b-99ae-9fa3e4a6c025.png)

But for me it looks more as an **enhancement** rather than a bug: Clem, could you please let Qirx look for the 320x240 SPI pic and show it there? Otherwise it breaks the layout as described above.

**Comment by softsyst** [comment]
**@andimik**'s suggestion is what is already implemented in the code. The simple search algo looks for an image which is non-quadratic and has a width of 320. If none is found it takes the largest present.

Thanks to **@cgfan** providing the pictures I copied the SPI he provided into the SPI directory and could test it. It's a non-obvious bug in the software. These pictures and also the ones of "Radio SPR" do not have the usual Dpi (dots per inch) value of 96, but 300. When checking the "Width" property of the BitmapImage, one gets a wrong value, as the "Width" is measured in units of 1/96dpi. This is the reason for the ugly picture display, while all other pictures have 96Dpi, resulting in "Width" to be the same as "PixelWidth" (another property of "BitmapImage").

After a quick correction, the pictures display properly.

![image](https://user-images.githubusercontent.com/51386375/235649077-bf6d5dd6-967c-4c14-ae59-0c63210c3949.png)


Clem

**Comment by andimik** [comment]
> as the "Width" is measured in units of 1/96dpi.

Oh, interesting. Thanks for the explanation.

**Comment by edd-cgfan** [comment]
Thank you  Clem for the explanation and the interesting information about your investigation.

> ... Much better than most of the other crap.

Yes, unfortunately.
Nevertheless, you made me smile.

cgfan

**Comment by andimik** [comment]
BTW: even "our" mux here in Austria had the same problem. Some pics are 300dpi like Radio Austria.

# good example (Antenne Österreich)

![Screenshot (405)](https://user-images.githubusercontent.com/24510556/236629019-02745397-c889-4ec2-a902-2904b19c22b4.png)

# bad example (Radio Austria) 

![49ED1A31](https://user-images.githubusercontent.com/24510556/236629021-4cc29a74-8c18-4f00-9e98-d8b8b25e7c42.png)
![Screenshot (404)](https://user-images.githubusercontent.com/24510556/236629024-7a3838f3-fc49-442b-a40b-457de5072448.png)

# other bad example with Arabella Relax

should be that pic
![AC45C97E](https://user-images.githubusercontent.com/24510556/236629116-509ca5a7-6e4d-459e-aa6a-3a453e2bbfc0.png)

but this is used
![D1EE01CB](https://user-images.githubusercontent.com/24510556/236629138-2325d1d3-f472-48c4-ae5e-12742f861bbd.png)

![Screenshot (403)](https://user-images.githubusercontent.com/24510556/236629028-d7687463-ae4a-4980-90d8-2f8700a2f4d3.png)

**Comment by softsyst** [comment]
Please someone check it if it's ok now. Thanks

**Comment by edd-cgfan** [comment]
Hi Clem,

The 2 above mentioned logos in my initial post look okay now with 4.0.9.

cgfan

**Comment by softsyst** [comment]
Again, many thanks for your very fast response. I close that one.
