### ISSUE TITLE
Both HW and SW AGC should be selectable

### ISSUE THREAD

**Issue by rf-oldie** [softsyst/qirx_issues#88]
Starting with V4.0.6 AGC for RTL-SDR devices was changed to "Hardware".
This has significantly reduced settling time and often avoids overload situations, but in parallel accuracy of absolute level scale decreased. More than before the design of the RTL stick has an influence on the level and especially at low levels an error of up to 10 dB may occur. The effect can be checked easily by watching the level spectrum while switching between automatic and manual gain.
A good solution would be to add another mode:
1. manual gain with absolute level
2. SW AGC with absolute level
3. HW AGC with level scale relative to fullscale

**Comment by softsyst** [comment]
The reason why I hesitate to realize it is mainly GUI issues, but not only. Programming a SW AGC with so few control steps is always a compromise. The realization of the optimal response times is a hassle. 

For the GUI, currently, there is one single checkbox for the AGC. This is the most comfortable solution for the users. As it would affect only the RTL-SDR devices, the new SW/HW AGC switch should be on the specific R820T, E4000, FC0013... pages. Not nice at all. Additionally, would the whole "zoo" react in the identical way or would each of those need their own set of AGC parameters?

For those who need the absolute measurements, the manual gain would be necessary. Isn't this enough?
Thus, although I am still undecided, I am inclined to reject it if there are no other strong arguments.

A consistent GUI should not be undervalued.

**Comment by softsyst** [comment]
I tag it as "enhancement" as probably @old-dab will implement it in his rtl(2)_tcp.

**Comment by softsyst** [comment]
Should work in 4.1.1. I close it
