### ISSUE TITLE
Overload indicator

### ISSUE THREAD

**Issue by rf-oldie** [softsyst/qirx_issues#89]
When operating QIRX with manual gain it is often difficult to find the best setting. For optimum dynamic range gain should be close to full scale but w/o overload of samles. In DAB mode tis can be viewed in the IQ data diagram.
A level indicator (similar to the VU meters of old tape recorders) could help, e.g. a bargraph showing peak and average value of the actual IQ samples stream.

**Comment by softsyst** [comment]
Thanks for the input!

If an overload indicator, shouldn't it work also for the other modes like WFM? For my feeling, the better place would therefore be the rtl(2)_tcp, where this info should be available. 
This would be in line with the sdrplay solution. Sdrplay provide two overload events, which control the "Overload" warning message on the qirx GUI. They are: "Overload detected" and "Overload corrected". 
This works perfectly. Output is on the Main Frontend page.

The bargraph would be a different item.

**Comment by softsyst** [comment]
As @old-dab confirmed to realize it in rtl(2)_tcp, I close this one. 
Please feel free to open an issue about the level indicator.
