### ISSUE TITLE
QIRX support SDRplay RSPdx

### ISSUE THREAD

**Issue by displaydriver** [softsyst/qirx_issues#9]
Unfortunately the SDRplay RSPdx does not work with QIRX because it is not supported by the API 2.13. What I've read needs API 3.07 this API support the RSPdx

https://www.sdrplay.com/downloads/
API/HW Driver 3.07 | RSP Control Library + Driver | 08-Jun-2020 | Release Notes |   |  
Supports all RSPs. Required for 3rd party applications & developers

**Comment by softsyst** [comment]
QIRX support for  API V3 is in preparation. I made already tests with it, but no stable release yet.
Thanks for the suggestion!

**Comment by softsyst** [comment]
RSP3_tcp (binary contained in the 3.2.2 qirx package) cooperates with sdrplay API3.09 and supports the RSPdx.

**Comment by softsyst** [comment]
@displaydriver : In case you read here, I hope you can consent to my closing this one. If not, or something should not be ok with the new RSP3_tcp, please feedback.

Clem
