### ISSUE TITLE
Level indicator

### ISSUE THREAD

**Issue by rf-oldie** [softsyst/qirx_issues#90]
In my issue #89 I had two kinds of indicators in my mind: overload and level.
Both are helpful for setting and monitoring manual gain. As the overload function seems to become implemented soon, I will repeat the idea of a level indicator, e.g. a bargraph showing peak and average value of the actual IQ samples stream. (usable not only for DAB  but for all modes)

**Comment by softsyst** [comment]
Thanks for this new issue. This would certainly a very useful enhancement.

**Comment by softsyst** [comment]
4.1.1: SNR of peak value is shown in WFM and NFM, AM, service power in DAB, WFM.
