### ISSUE TITLE
No DAB+ Audio (Ver 4.0.8)

### ISSUE THREAD

**Issue by m0jwb** [softsyst/qirx_issues#91]
New to this community so go easy!- been using QIRX for approx 2 years and currently using V4.0.8 but there is no audio on any DAB+ stations - Reinstalled but still no DAB+ audio - can anyone point me in the right direction to solve this? - I have also tried with previous versions but with same results

**Comment by andimik** [comment]
So, as soon as you have installed 4.0.8 you have no audio even when you uninstall it and install previous version?

Have you checked the Audio settings in Windows? Seems you have muted just Qirx.

**Comment by m0jwb** [comment]
The audio is fine on DAB but is missing on DAB+ stations - this is with a completely new fresh install of any of the V.4 versions - I did have it working about a month ago but the problem seems to have started after I upgraded to V4.0.8

**Comment by m0jwb** [comment]
**Update** : This issue is now resolved.
Installed QIRX4 on a second machine - and no problems with DAB+ audio. Made some comparisons between the two machines and discovered that on the problem machine I had a Windows Firewall issue which I resolved. I also noticed that the audio routing of DAB+ on Win11, it was trying to use a different output device than that for DAB (thanks 'andimik')

**Comment by andimik** [comment]
You are welcome!
