### ISSUE TITLE
10D DAB+ W-VL

### ISSUE THREAD

**Issue by WIHDIA** [softsyst/qirx_issues#92]
Hi,

On 10D DAB+ W-VL the TII's are shown, but there's nothing on the map. Could it be due to the odd 0064 Code?

![afbeelding](https://github.com/softsyst/qirx_issues/assets/53539654/81513f52-649c-4254-9813-cb12108249b5)

Recording: https://e.pcloud.link/publink/show?code=XZFohuZDgMN7F2ffcJ2LF40kpNb1h2CIGsX

73
Kind regards

Herman Wijnants

[My logblog](https://www.wijnants.info/fmdx/)
Belgium editor [fmlist.org](https://www.fmlist.org/)

**Comment by softsyst** [comment]
Hi Herman,

Thanks for the file! This Ensemble is keeping us busy now for the 2nd time, see #38, covering a similar issue.
The 0064 code is not "odd", it is wrong, as it indicates a Country Code of zero. Belgium has 6. Standard 6.4.1. A country code of zero doesn't exist.

Then, you mentioned that you would write them about their wrong numbering. Did you? Did they respond?

Technically, in the software it is an incompatibility between character strings and hexadecimal number. The EId's are hex numbers, but represented in the database as strings. Usually no problem, except when leading zeros show up, as in that case. Now I changed the program that it accepts leading zeros. This makes the xmitters show up on the map, like so:

![WrongEId_0064](https://github.com/softsyst/qirx_issues/assets/51386375/6a6ffb02-62ee-48d4-b086-d8a60700c8ab)

Please note that they have the same issue with the SId's, as you can see on the screenshot. There, I did NOT make this change, as the SId's are not always four digits long. There are also 6-digits SId's, which would possibly lead to other unwanted side effects.

Maybe you can try to get some info about this situation from the operator or perhaps a Belgian regulator. It would be interesting.

Anyway, thanks for this input! The change should show up in the next release.

73
Clem

**Comment by WIHDIA** [comment]
**Hi Clem,**
 
> Thanks for the file! This Ensemble is keeping us busy now for the 2nd time, see #38, covering a similar issue. The 0064 code is not "odd", it is wrong, as it indicates a Country Code of zero. Belgium has 6. Standard 6.4.1. A country code of zero doesn't exist.

**I know and it has been pointed out to 10D guys.**

> Then, you mentioned that you would write them about their wrong numbering. Did you? Did they respond?

**I contacted them on April 22, 2022 and never got a reply.**

> Technically, in the software it is an incompatibility between character strings and hexadecimal number. The EId's are hex numbers, but represented in the database as strings. Usually no problem, except when leading zeros show up, as in that case. Now I changed the program that it accepts leading zeros. This makes the xmitters show up on the map, like so:
> 
> ![WrongEId_0064](https://user-images.githubusercontent.com/51386375/241559028-6a6ffb02-62ee-48d4-b086-d8a60700c8ab.jpg)
> 
> Please note that they have the same issue with the SId's, as you can see on the screenshot. There, I did NOT make this change, as the SId's are not always four digits long. There are also 6-digits SId's, which would possibly lead to other unwanted side effects.

**I noticed that too. No // with the PI codes used on FM at all.**
 
> Maybe you can try to get some info about this situation from the operator or perhaps a Belgian regulator. It would be interesting.

**I'll certainly try again. One never knows it might work :-)**
 
> Anyway, thanks for this input! The change should show up in the next release.

**Thanks!**
 
> 73 Clem

**Comment by softsyst** [comment]
Thanks, Herman!

In the obviously improbable case that you get an answer you might wish to publish it here or elsewhere. I assume you can agree that I close this for now.

73,
Clem
