### ISSUE TITLE
Recording and TII log txt

### ISSUE THREAD

**Issue by davidvisser1** [softsyst/qirx_issues#93]
Clem,

Playing a wav file in the Recorder the slider gives Time passed and the total recorded time.
Viewing the TII logger txt file You see the recorded time in UTC

I think this is very uncomfortable to look up for this logging in the Recorder.....
Why not view in the Recorder also the UTC time with the slider. 

David Visser

**Comment by softsyst** [comment]
Hi David,

Maybe you are talking about a raw file, not a wav file. Qirx does not replay wav files, it records them as audio files.

Replaying a raw file, you might have a look at the "Signal" tab. It contains the recording date as UTC.
The info below the slider is the expired time and the remaining time of the recording, not the total time.

![image](https://github.com/softsyst/qirx_issues/assets/51386375/b0111c96-4141-4bf8-ac2d-91a9f3a93b1d)

Thus, all your requested info should be available.

**Comment by davidvisser1** [comment]
Clem,

Ai.. sorry. Of course it must be raw files.  Don't saw the signal tab..
I am becoming an old man, hi

David Visser

**Comment by softsyst** [comment]
No problem, David. I know some Documentation would be not bad. But...
If hope you can agree that I close this.

**Comment by davidvisser1** [comment]
Sorry Clem,

Trying again but in the recorder I don't see on the signal tab the right info.
On date/time tab I see 0000000
Also device is unknown.

David Visser

**Comment by andimik** [comment]
I guess then the recording does not include xml header, right?

**Comment by softsyst** [comment]
Thanks, @andimik, for this interpretation. The xml header is indeed necessary. 
David, please try to make a recording with a current version of qirx. On replay, the info should be there.

**Comment by davidvisser1** [comment]
Using Qirx V4.0.8 here with RTL2-tcp dongle.  Where can I found the 
install exe file to re-install the program.

Below 2 screen shots:




------ Original Message ------
From "softsyst" ***@***.***>
To "softsyst/qirx_issues" ***@***.***>
Cc "davidvisser1" ***@***.***>; "Author" 
***@***.***>
Date 3-6-2023 10:32:17
Subject Re: [softsyst/qirx_issues] Recording and TII log txt (Issue #93)

**Comment by davidvisser1** [comment]
Clem,

Problem solved (I hope).
Execute before the start of Qirx:  rtl_tcp.exe ; start Qirx and the new 
recording is OK.

The cause of the problem is probably the use of the dongle in another 
program (Sdr Console).
In that case you have to start rtl_tcp.exe first and after that  Qirx (I 
think).

David V


-- Original Message ------
From "softsyst" ***@***.***>
To "softsyst/qirx_issues" ***@***.***>
Cc "davidvisser1" ***@***.***>; "Author" 
***@***.***>
Date 3-6-2023 10:32:17
Subject Re: [softsyst/qirx_issues] Recording and TII log txt (Issue #93)
