### ISSUE TITLE
Recording issue

### ISSUE THREAD

**Issue by davidvisser1** [softsyst/qirx_issues#94]
Clem,

A question about recording in Qirx.
Good conditions tonight; turned on the recorder and am now playing back looking for loggings via the TII logger.
Now it appears that the tape does not always indicate the right channel, there is a delay......

Example:
On channel **8D** log at some point (according to TII logger) states:  **NDR NDS OL**: thats correct , but a screenshot from the recorder at the same time indicates : channel **8C.**

This is incorrect. Germany has no NDR NDS OL on channel 8c, but on 8d, but I don't see channel 8d appear on the screen.
So there is a delay. Is this a known problem ? Am I doing something wrong ?

David Visser
![test](https://github.com/softsyst/qirx_issues/assets/13683761/c09f2f86-5f06-456b-9c90-99b1b35ad72a)

**Comment by softsyst** [comment]
Hi David,

For this to investigate, I needed a raw file with the recording or at least the critical part showing the error.

Clem

**Comment by davidvisser1** [comment]
Clem,
Raw file too big, so I attached a new screenshot of tonight
Ch 9c is not correct , must be 9b.
![9c nds lg onjuist](https://github.com/softsyst/qirx_issues/assets/13683761/c40972cc-c6bb-4207-929e-378ccd47fbe9)

**Comment by WIHDIA** [comment]
Hi David

https://www.sendbig.com/ might help, although it could take a while.

73

Herman
[My logblog](https://wijnants.info/fmdx/)
Belgium[ fmlist](https://www.fmlist.org/) editor

**Comment by andimik** [comment]
I fear the problem has nothing to do with Qirx, but with rtl_tcp.

I have seen some false alarms in the past months where people reported muxes on neighbor channels.

**Comment by softsyst** [comment]
David, Herman,

up- and downloading a file of e.g. 100GB makes no sense, in my opinion. I see two possibilities:

- Either catch the error in a smaller file
- Or cut out a part of such a large file where the cut-out part contains the error. This would be possible e.g. with a Hex Editor like  HxD, or perhaps other tools. Cut parts should replay well, if the cutting position takes place on an even byte position.

Currently, I would have problems download 100GB files, as my disk currently has a free space of 56GB.

From the screenshots it is not possible to find such an error. 

Clem

**Comment by davidvisser1** [comment]
Hi all,

I'm afraid Andimik  is right: the culprit is the RTL stick; we will have to live with it.

David V

**Comment by softsyst** [comment]
@andimik,

How could the rtl_tcp be the culprit? For me, it's not easy to imagine. I assume some timing problem in the scanner. Some raw file would be good, even if the repair might not be easy, as usual with sporadic behavior.

**Comment by softsyst** [comment]
I leave this open for some days. In case someone can send me a raw file to investigate it, I would do so. Otherwise I'll close it.

**Comment by andimik** [comment]
Well, due to the fact that also other tools (like Qt-DAB) connected via rtl_tcp show the same problem, this seems to be not a Qirx issue and shall be closed in my opinion.

I don't think a raw file will help.

**Comment by softsyst** [comment]
No new information available. I close it. Please feel free to re-open if you think it necessary.
