### ISSUE TITLE
Changing the gui of the recorder

### ISSUE THREAD

**Issue by davidvisser1** [softsyst/qirx_issues#95]
Hi Clem,

Recording again (hi)
On this screenshot of the recorder You see:

1. Expired time          02:31:45
2. Total   time          04:10:05
3. Recording started at: 00.09.09 utc

In this example: Why not change the expired time in 02:40:54  (= 00:09:09 + 02:31:45)
Now it is much easier to compare this time it with the TII log file.

![recorder gui](https://github.com/softsyst/qirx_issues/assets/13683761/91054781-96da-4ad0-9902-9c1e5551ac20)

David Visser

**Comment by softsyst** [comment]
Hi David,

Hasn't a similar topic been closed already? Anyway:

1. The 04:10:05 is NOT the total time, it is the remaining time. Total time is 6h, 41min, 50seconds. Must be a pretty large file btw, about100GBytes? Please notice (again) that the duration is indicated in the field "Duration" below.
2. You ask (quote)
   "Why not change the expired time in 02:40:54 (= 00:09:09 + 02:31:45)"

 This would no longer be an "expired time" but the calendar time.  Only wording, I know. The solution you suggest would of course not be sufficient, as you needed to add not only the time of day, but also the date, in case you make recordings crossing midnight, which seems to be very probable when recording files for more than six hours.

 What would you display when replay a recording from another app not knowing the date? Leave it open? Write 00-00-00 to indicate it's unknown, as in the "Recording Date" field?  I don't like the idea. 

The present solution has been proved working and being robust over the years.
 
A simple remedy to suit your special needs would be a simple addition of starting time/date with the expired time, e.g. in Excel. Much simpler and less effort than changing the app in the way you request. 

Clem

**Comment by davidvisser1** [comment]
Conditions were very good last night; so I let the recorder run for a few hours on my external drive (8TB). No probllems

I just had a simple question: is it possible that the "expired time" clock just shows the current utc time ; much easier now to go to the recorder screen later when searching interesting Dx logs from the TII log.

David V

**Comment by softsyst** [comment]
As discussed, this will not be realized. I close the issue.
