### ISSUE TITLE
The licence is not bound to the machine, but also to the OS on it. Very annoying after Windows crashes.

### ISSUE THREAD

**Issue by schluckspecht** [softsyst/qirx_issues#97]
In the licence text you can read: "Machine binding: Each license key will be bound to the machine where it is used. The binding happens on first use of a license key." I thought, things like processor id or mac addresses were used. But why is a licence invalid after a reinstallation of the OS, when the PC crashed completely and you have to install the OS again?

**Comment by softsyst** [comment]
The machine binding is also invalidated when the OS needs a new install or the HW is changed significantly. This is a decision of the OS, not mine. Please tell me your registration name or email address or license key, e.g. by email or here in this thread, and I will reset the machine binding. The license key will remain valid.

**Comment by softsyst** [comment]
Closing this one, as no further actions or comments are required.
