### ISSUE TITLE
Suggestion for better handling of the RSP LNA State slider control

### ISSUE THREAD

**Issue by edd-cgfan** [softsyst/qirx_issues#99]
Hi Clem,

It would be nice if the slider control could be controlled with the arrow keys.
Especially, if one is operating "in the field" without a mouse using only the built-in mousepad. 

Regards,
cgfan

**Comment by softsyst** [comment]
Thanks for re-opening this in its own issue. 
Clem

**Comment by softsyst** [comment]
Hi cgfan,

I was just experimenting with changing a slider with the keyboard. It is already working in the current version, however not with the arrow keys, but with PgUp, PgDn keys.

To enable it with the arrow keys would be a minimal change, but I doubt this will satisfy your need, according to the description of your use-case.

Before being able to change the slider using the keyboard, you need to give it the focus. How do you do it? You guess it: with the mouse, by clicking on the slider! But exactly this should be avoided!

QIRX is not designed to be operated by the keyboard. It could be done, but for this a concept would be needed working for all input possibilities in a consistent way, with  a visual feedback which control got the keyboard focus. This does not seem to be a small task, which I hesitate to spend time on currently.

Clem

**Comment by edd-cgfan** [comment]
Hi Clem,

Sorry for delay. I have been in "in the field" but with different tasks.
Thanks for the investigation: Yes, it works like you described it.
This should meet my requirements. No further work should be spent on it.
About the Focus: I don't have WPF experience. However, I remember older Visual Studio class libraries where the focus was controlled with the tab key and the respective control was also highlighted in the window, so one could walk through to the controls until you reached the desired one.
It works similar here except without highlighting every control.
As said before, this is okay for me.
Thanks again.

Regards,
cgfan

**Comment by softsyst** [comment]
Hi cgfan,

Thanks for feedback. No problem with the delay. "The field" always has priority!
Yes, of course I know what you describe. One can tab through the controls, but with many controls you need a plan about the sequence, some need a tab, some not, etc.
Nevertheless I will think about this issue and try to find a solution and let you know if I got a result. In the meantime, I close this one. In the early times of WinForms and MFC (still existing!) one could activate a menu item with Alt+some letter. Was rather convenient. Will see whether such a thing still exists, to navigate the focus to the arrow keys.

Thanks for your input!

Clem
